### ISSUE TITLE
Incorrect rendering of calendar when navigate fast

### ISSUE THREAD

**Issue by webartistse** [krystalcampioni/vue-hotel-datepicker#101]
If the user navigate fast and mix up with clicking next/previous the calendar is starting to render months in wrong order or render duplicates. This is quite easy to reproduce in Chrome on Mac and Win.

![screenshot 2018-10-22 at 10 27 54](https://user-images.githubusercontent.com/3966652/47284012-eb7f0f80-d5e5-11e8-802b-96e6cf0ca1fd.png)
![screenshot 2018-10-22 at 10 27 38](https://user-images.githubusercontent.com/3966652/47284014-ec17a600-d5e5-11e8-8b59-4e232389e9ab.png)

**Comment by krystalcampioni** [comment]
Fixed via https://github.com/krystalcampioni/vue-hotel-datepicker/pull/105
