### ISSUE TITLE
:disabledDaysOfWeek not working as expected

### ISSUE THREAD

**Issue by thepatres** [krystalcampioni/vue-hotel-datepicker#108]
Hello, did someone noticed that disabledDaysOfWeek is not working?

Using this: :disabledDaysOfWeek="['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday']"

but my calendar did not disabled any day.

I am using version 2.4.1

**Comment by premiermatt** [comment]
Experiencing the same issues. This is one of the reasons I wanted to use this comp other others.

**Comment by sofianester** [comment]
use :disabledDaysOfWeek="['Monday', 'Tuesday', 'Wednesday']"

**Comment by matiasperrone** [comment]
I am interested in this issue.
I understand what you mean, but it could be a compatibility breaking change. We should change the prop name in order to correct this issue, maybe by converting this Array of string as numbers, so it does not depend on i18n.
