### ISSUE TITLE
Datepicker crashes if starting-date-value and ending-date-value are both in december 2018

### ISSUE THREAD

**Issue by geroldboehler** [krystalcampioni/vue-hotel-datepicker#117]
### Description

The title says it all. If both starting-date-value and ending-date-value are in december 2018, the datepicker crashes. But it only seems to happen for 2018, 2017 and 2019 seem to work. Am i missing something?

### Code sample 
```
<hotel-date-picker
  single-date-selection
  :starting-date-value="new Date('2018-12-01')"
  :ending-date-value="new Date('2018-12-02')"
/>
```
### Steps to Reproduce
Run code sample above.

**Expected behavior:**
Starting and ending dates should be set properly

**Actual behavior:**
Datepicker throws TypeError: Cannot read property 'days' of undefined

### Datepicker Version
https://github.com/dseidl/vue-hotel-datepicker/tree/develop

**Comment by geroldboehler** [comment]
Hi guys, any news on this? thx!

**Comment by abclive** [comment]
Hey guys, sorry we won't have time to do a PR as the code branched out quite a bit for our needs. The fix is rather simple if you follow the steps I've described above, perhaps someone could do a PR using that info as a starting point.

**Comment by pvrsouza** [comment]
still happening?  I couldn't reproduce

**Comment by pvrsouza** [comment]
> set the dates of the next month at initialization. For example: now - February, set the dates of March and you will see that error.

Can you send the error?

**Comment by SpinyMan** [comment]
https://yadi.sk/d/HvZASrZuVvac_w

**Comment by krystalcampioni** [comment]
@SpinyMan could please send the snippet of how you're using the datepicker? Tried reproducing now using dates of March but wasn't able to reproduce.

**Comment by SpinyMan** [comment]
Works (current month's value):
```
<HotelDatePicker :startingDateValue="new Date('2019-02-20')"></HotelDatePicker>
```
Doesn't works (with future dates):
```
<HotelDatePicker :startingDateValue="new Date('2019-03-20')"></HotelDatePicker>
```

**Comment by abclive** [comment]
@krystalcampioni @SpinyMan This is the fixed beforeMount for that issue, I explained a bit more above what we did. I don't have time for a proper PR but I hope it helps

```javascript
beforeMount() {
      fecha.i18n = {
        dayNames: this.i18n['day-names'],
        dayNamesShort: this.shortenString(this.i18n['day-names'], 3),
        monthNames: this.i18n['month-names'],
        monthNamesShort: this.shortenString(this.i18n['month-names'], 3),
        amPm: ['am', 'pm'],
        // D is the day of the month, function returns something like...  3rd or 11th
        DoFn: function (D) {
          return D + ['th', 'st', 'nd', 'rd'][D % 10 > 3 ? 0 : (D - D % 10 !== 10) * D % 10];
        }
      };
        if(this.checkIn &&
        (this.getMonthDiff(this.getNextMonth(new Date(this.startDate)), this.checkIn) > 0 ||
        this.getMonthDiff(this.startDate, this.checkIn) > 0)){
          this.createMonth(new Date(this.startDate));
          const count = this.getMonthDiff(this.startDate, this.checkIn)
          let nextMonth = new Date(this.startDate)
          for(let i = 0; i <= count; i++){
            let tempNextMonth = this.getNextMonth(nextMonth)
            this.createMonth(tempNextMonth)
            nextMonth = tempNextMonth
          }
          if(this.checkOut && this.getMonthDiff(this.checkIn,this.checkOut) > 0){
            this.createMonth(this.getNextMonth(nextMonth))
            this.activeMonthIndex = 1
          }
          this.activeMonthIndex += count
      }else{
        this.createMonth(new Date(this.startDate));
        this.createMonth(this.getNextMonth(new Date(this.startDate)));
      }
      this.parseDisabledDates();
    },
```

**Comment by Sebarkar** [comment]
Same problem, if I choice today (2019-04-16 - April days in may - there is [Vue warn]
Error in render: "TypeError: Cannot read property 'days' of undefined"

Another month selection works well.

```
        <HotelDatePicker :endingDateValue="new Date (2019-05-22)"
                         :startingDateValue="new Date (2019-05-15)"
        ></HotelDatePicker>
```
