### ISSUE TITLE
Can't use singleDateSelection

### ISSUE THREAD

**Issue by Bennecer** [krystalcampioni/vue-hotel-datepicker#122]
### Description

Hi, I'm trying to get the singleDateSelection working. I might be using it wrong ? I added :singleDateSelection="true" in the tag HotelDatePicker but I still have the daterangepicker when I do that. Has anybody got it working ? Is it supposed to work yet ? Thank you in advance !

### Datepicker Version

vue-hotel-datepicker@2.7.1

**Comment by annapolar** [comment]
You can try :singleDaySelection="true"
I added this prop and it works.

**Comment by Bennecer** [comment]
I works ! Thank you 😄

**Comment by ahallez** [comment]
The option is indeed singleDaySelection instead of singleDateSelection.
The documentation mentions the wrong option name.
