### ISSUE TITLE
Display inline pickers

### ISSUE THREAD

**Issue by Mushr0000m** [krystalcampioni/vue-hotel-datepicker#128]
Is there a way to use it with as an inline picker ? We need to always let the pickers visibles and not in absolute position.

**Comment by abclive** [comment]
We've implemented that functionnality on our fork, again we don't have time to do a PR but if anyone wants to have a go at it, [here's our updated file](https://github.com/CollectiveDesign/vue-hotel-datepicker/blob/compiled/src/components/DatePicker.vue).

Just look for the openMode prop in the code.

**Comment by PascalAOMS** [comment]
Hey @abclive 
Any plans on merging this?
We are super interested in this openMode.

Thank you.

**Comment by abclive** [comment]
Hey @PascalAOMS sorry just noticing your message now. We curently have no plans of merging this fork as it contains a lot of hacks for our specifics needs and is now far behind the master branch.

However our repo is open and anyone who wants to implement this can use our implementation as a base for a PR.

**Comment by matiasperrone** [comment]
Hi, I be working on this.

**Comment by matiasperrone** [comment]
Hi, I am a little swamp right now, so it could take a while.

**Comment by matiasperrone** [comment]
Done in v4
