### ISSUE TITLE
Button to load more months not appearing on mobile view

### ISSUE THREAD

**Issue by tbyte80** [krystalcampioni/vue-hotel-datepicker#135]
### Description

This problem occurs when using the datepicker with default settings on small viewports (mobile).
It requires a lot of swiping to trigger more months to be displayed. There is an PR ( https://github.com/krystalcampioni/vue-hotel-datepicker/pull/63 ) that addresses this by introducing a button to load more months, however I didn't find any way to make it appear, also in the examples I couldn't find any with that button.

### Code sample 
Just the default datepicker

### Datepicker Version

2.6.4

Found the cause. The styles are there but they are applied to a button tag where as the next--mobile class sits on a <div type="button" . If I change div to button everything works just fine. Still needs a fix though.

**Comment by jebkor** [comment]
It appears that writing some text in the button, while it's a div, will make the button appear.
