### ISSUE TITLE
Choose display month

### ISSUE THREAD

**Issue by Shakkam** [krystalcampioni/vue-hotel-datepicker#137]
Hi from France :)
I'm a new user of your datepicker. We don't use it for hotel reservation so the start date can be 3, 6 .... X months before.

A simple but great feature would be to be able to specifiy a "displayDate", who will force the left month.

For example, if I set a startDate to "2016-01-01" and a displayDate to "2019-04-11", the date picker will open with an April 2019 panel on the left and May 2019 on the right.

I hope my english is clear enough :)

**Comment by matiasperrone** [comment]
Hi from Argentina @Shakkam, your English is cool.
I am not sure what are you asking... can you provide us with a PR?

**Comment by matiasperrone** [comment]
Is it possible that you need to use "startingDateValue"?

**Comment by Shakkam** [comment]
Hi ! I'm not working on it anymore... But thanks for your answer :)

Le jeu. 21 nov. 2019 à 21:55, Matias Perrone <notifications@github.com> a
écrit :
