### ISSUE TITLE
Lost picked data when press backspace.

### ISSUE THREAD

**Issue by hrabryi** [krystalcampioni/vue-hotel-datepicker#15]
When picked some data and outfocus from element and press backspace(delete) button, the picked data are reset. Can you fix this issue?
I find this code in hotel-datepicker.js:
```
// If the user presses delete or backspace, clear the selection
        document.addEventListener('keydown', KeyCheck);

        function KeyCheck(event) {
            var KeyID = event.keyCode;
            if (KeyID === 8 || KeyID === 46) {
                self.clearSelection();
            }
        }
```

Can you remove it? It a really the big problem, because if you have other fields to input some data and make mistake, then press delete and ooops! you lost you piked data.

**Comment by krystalcampioni** [comment]
It was solved by v2.0.0
