### ISSUE TITLE
Selecting dates

### ISSUE THREAD

**Issue by BrotherSymeon** [krystalcampioni/vue-hotel-datepicker#157]
### Description
When the overlay that displays the dates to choose from is showing, I can only see 2 months and can't scroll to any others

**Expected behavior:** [What you expected to happen]

Expected to be able to scroll to see months in the future

**Actual behavior:** [What actually happened]

can only scroll to see two months: the current one and the next month

### Datepicker Version

 "vue-hotel-datepicker": "^2.6.4",

**Comment by zangab** [comment]
if this problem is on mobile screens, you could reuse our hotfix solution:
`<script>
import throttle from 'lodash.throttle';
import HotelDatePicker from 'vue-hotel-datepicker';

export default {
  extends: HotelDatePicker,

  methods: {
    renderNextMonth: throttle(function () {
      if (this.activeMonthIndex < this.months.length - 2) {
        this.activeMonthIndex++;
        return
      }

      let firstDayOfLastMonth;

      if (this.screenSize !== 'desktop') {
        firstDayOfLastMonth = this.months[this.months.length - 1].days
          .filter((day) => day.belongsToThisMonth === true);
      } else {
        firstDayOfLastMonth = this.months[this.activeMonthIndex + 1].days
          .filter((day) => day.belongsToThisMonth === true);
      }

      if (this.endDate !== Infinity) {
        if (fecha.format(firstDayOfLastMonth[0].date, 'YYYYMM') === fecha.format(new Date(this.endDate), 'YYYYMM')) {
          return
        }
      }

      this.createMonth(
        this.getNextMonth(
          firstDayOfLastMonth[0].date
        )
      );

      this.activeMonthIndex++;

      this.$nextTick(() => {
        const lastElement = [...this.$el.getElementsByClassName('datepicker__month')].pop();

        if (lastElement && window.matchMedia('(max-width: 768px)').matches) {
          lastElement.scrollIntoView({ behavior: 'smooth' });
        }
      });
    }, 200),
  }
};
</script>
`
