### ISSUE TITLE
Picker breaks when selecting a date and switching months

### ISSUE THREAD

**Issue by Rias500** [krystalcampioni/vue-hotel-datepicker#16]
The date picker breaks when trying to select a check-in date, then going to the next month and trying to select a new date, all days become disabled. Same for when you return back to the month

Select a date:
![image](https://user-images.githubusercontent.com/3626559/31552370-93a8cfaa-b037-11e7-83f8-3dd791dbb852.png)

Click on the arrow for the next month:
![image](https://user-images.githubusercontent.com/3626559/31552377-9ad4081c-b037-11e7-8393-090eced89b0c.png)

Go back a month:
![image](https://user-images.githubusercontent.com/3626559/31552383-9ff2572c-b037-11e7-9fc2-a658742f6d69.png)

**Comment by Rias500** [comment]
This is solved somehow by setting "enableCheckout" to "true" though I don't know why this would be, the dates should not be disabled.

**Comment by krystalcampioni** [comment]
Fixed by https://github.com/krystalcampioni/vue-hotel-datepicker/pull/19
