### ISSUE TITLE
Emit more events

### ISSUE THREAD

**Issue by guillaumebriday** [krystalcampioni/vue-hotel-datepicker#161]
### Description

emit more events like `@close`, `@open` or `@clear`. It could be very useful to know when to submit a form for example.

### Datepicker Version

Version: 2.6.4

**Comment by matiasperrone** [comment]
Well I will be adding this on v4 (total rewrite)

**Comment by matiasperrone** [comment]
There are some more in v4.0.0-beta.2, probably in the RC I am going to add all the possible events.

**Comment by matiasperrone** [comment]
try v4 please!
