### ISSUE TITLE
Conflicting package name of vue-hotel-datepicker

### ISSUE THREAD

**Issue by mhp-borisbojic** [krystalcampioni/vue-hotel-datepicker#167]
Hey,

there is another package with the very same name as yours:

https://github.com/northwalker/vue-hotel-datepicker

This gives my current project (and version selection) a headache. ;)

Would you consider changing the name?

**Comment by matiasperrone** [comment]
Hi, @mhp-borisbojic I'm one of the mantainers... why do you want that? Why it is a headache?... once you set the require in npm, it does its magic...

**Comment by mhp-borisbojic** [comment]
Well, back then (this was October 2019!) it was a headache, because npm wanted to install the other package - but it's working now. ;)
