### ISSUE TITLE
Feature request: Show price for the night

### ISSUE THREAD

**Issue by dubemarcantoine** [krystalcampioni/vue-hotel-datepicker#171]
### Description
I am currently creating an online booking website and use this library. What I need is to display the prices for each nights which can change depending on the period of the year.

I started the development and would like to know if you would be interested in a PR of such a feature.

### Code sample 
https://github.com/dubemarcantoine/vue-hotel-datepicker

```
<DatePicker
                        :defaultPrice="123"
                        :priceRanges="priceRanges"
/>

data() {
            return {
                priceRanges: [
                    {
                        startDate: new Date(2019, 10, 29),
                        endDate: new Date(2019, 11, 1),
                        price: 500
                    },
                    {
                        startDate: new Date(2019, 11, 20),
                        endDate: new Date(2020, 0, 6),
                        price: 200
                    },
                ],
           }
}
```

It looks like this:
![image](https://user-images.githubusercontent.com/11211814/69825413-2f771780-11dd-11ea-8a78-2c019218a8f1.png)

**Comment by matiasperrone** [comment]
Marc, maybe you can provide us with a Pull Request?

**Comment by dubemarcantoine** [comment]
Sure, I'll do the PR next weekend as I'm in my finals week and have to study :smile:

**Comment by matiasperrone** [comment]
Hi @dubemarcantoine, do you have the PR?

**Comment by dubemarcantoine** [comment]
Hello @matiasperrone !
My bad I had totally forgotten.
There it is: https://github.com/krystalcampioni/vue-hotel-datepicker/pull/176

**Comment by matiasperrone** [comment]
I just about to add this to the [v3 branch](https://github.com/krystalcampioni/vue-hotel-datepicker/tree/v3.0.0). But with some changes:

The props are called `priceDefault` instead of `defaultPrice` and  `priceByDate` instead of `priceRanges`, and each "range" or date must have the following format: `{start: <Date>, end: <Date>, price: <Number or String>}`.

Still not commited yet, I didn't have the time to test propertly so... is a pre-alpha version

**Comment by matiasperrone** [comment]
I have pushed prealpha version on v3 branch... maybe you can take a look. 👍

**Comment by matiasperrone** [comment]
Check out v4.0.0-beta.2
