### ISSUE TITLE
Please add "onClose" event(Enchancement)

### ISSUE THREAD

**Issue by ayophanz** [krystalcampioni/vue-hotel-datepicker#177]
Please add "onClose" event suggestions

**Comment by matiasperrone** [comment]
Cool event...

**Comment by matiasperrone** [comment]
This will be added on v3, that I am currently working on.

**Comment by ayophanz** [comment]
That's great!!
thanks

**Comment by matiasperrone** [comment]
I am going to merge this issue with  #161
