### ISSUE TITLE
SECURITY VULNERABILITY!!!! 

### ISSUE THREAD

**Issue by ayophanz** [krystalcampioni/vue-hotel-datepicker#178]
![image](https://user-images.githubusercontent.com/24581584/71609167-5a300380-2bc1-11ea-968c-e7c0cf138952.png)

Update those packages in your package.json

**Comment by saniales** [comment]
please do this ASAP

**Comment by matiasperrone** [comment]
How may I reproduce this?

**Comment by saniales** [comment]
Just run `npm audit` or `yarn audit after installing the package

**Comment by matiasperrone** [comment]
Yeah, but I have found:

341 vulnerabilities found - Packages audited: 8317
Severity: 32 Low | 30 Moderate | 279 High

So is time to look at version 3... and correct some very old packages

**Comment by matiasperrone** [comment]
@krystalcampioni What do you think?

**Comment by tkima** [comment]
Just update the cssnano 3.10.0 dependency to cssnano 4.1.10?

**Comment by ayophanz** [comment]
thank you :) @matiasperrone for your time on this issue.

**Comment by matiasperrone** [comment]
I am going to move the code to the new version on all the dependencies so it'll be up to date, I will be moving to version 3.x to do so.

Also I am going to try to add all the pending PRs with new features.

Maybe also leaving pug lang behind... but I don't know just yet, maybe in the future ¿perhaps 3.1?🤔.

**Comment by ayophanz** [comment]
That's great

**Comment by krystalcampioni** [comment]
I'm totally up for removing pug. As much as I love it, we had quite a lot of people asking for removing it since I first released the package. 👍

**Comment by matiasperrone** [comment]
I am working on version 3, with pug in it in order to release it as soon as possible. I am also incorporating all the PRs, some with some changes.

I am very busy on work right now, so as soon as I can it will be available
