### ISSUE TITLE
The index file was not found to installation

### ISSUE THREAD

**Issue by Nightwing316DftPnk** [krystalcampioni/vue-hotel-datepicker#179]
the index file to the project was not found.

**Comment by matiasperrone** [comment]
@Nightwing316DftPnk I don't understand the issue here. 
Can you please explain in detail what should be fixed and why?

Do you prefer to write in spanish? I can do that.

**Comment by matiasperrone** [comment]
Please check `src/index.html`

**Comment by Nightwing316DftPnk** [comment]
Cuando instalo la librería vía NPM no instala el archivo index.ts no lo veo
dentro de la carpeta de no de
