### ISSUE TITLE
I can not start picker

### ISSUE THREAD

**Issue by rndmax** [krystalcampioni/vue-hotel-datepicker#180]
### Description

Hey. I tried to insert 'vue-hotel-datepicker' in a universal application in 'nuxtjs', however I could not achieve a positive result. Next, I installed the 'Hello World' application via 'vue-cli' and tried to add 'vue-hotel-datepicker' to it, but I also failed.
Here is the error I get:
Module not found: Error: Can't resolve 'vue-hotel-datepicker' in ...
That is, the module was not found!
I looked into the folder node_modules / vue-hotel-datepicke and found only:
node_modules/
package.json
README.md
License

### Code sample 
```
<template>
    <HotelDatePicker />
</template>

<script>
import HotelDatePicker from 'vue-hotel-datepicker'

export default {
  components: {
    HotelDatePicker,
  }
}
</script>
```

### Steps to Reproduce

1. vue create hello-world
2. npm install vue-hotel-datepicker --save
3. npm run serve

**Expected behavior:** Allow check-in and check-out on the same day with calendar

**Actual behavior:** Module not found

### Datepicker Version

2.7.5

**Comment by matiasperrone** [comment]
Sorry about that, its now fixed in the 2.7.6 version
