### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by sonia360** [krystalcampioni/vue-hotel-datepicker#181]
Possible to use the plugin in a non Single Page App?

**Comment by matiasperrone** [comment]
It's possible. I did not understand if that it's just the question.

**Comment by sonia360** [comment]
@matiasperrone Can you explain me how?  I think I do something wrong.

**Comment by matiasperrone** [comment]
I don't know how, please check the [issue template](https://github.com/krystalcampioni/vue-hotel-datepicker/blob/master/issue_template.md).

Keep in mind that I don't how are you using or deploying the app.

**Comment by matiasperrone** [comment]
If you can, explain what problems are you having or errors. 
Maybe a bit of code...?

**Comment by jefftrois60** [comment]
Hi @matiasperrone following sonia360 comments i'm wondering if you have as well a cdn link for me to use inside a php project. I don't want to have to install everything in my project and I only want to include a small calendar component inside my app. Is it possible? I've looked around and I haven't found a cdn option for your calendar like the other one, thanks

**Comment by matiasperrone** [comment]
All npm packages have free CDN access as `https://cdn.jsdelivr.net/npm/package@version/file`
For more information check https://www.jsdelivr.com/

**Comment by jefftrois60** [comment]
@matiasperrone 
We already tried those:
<div id="root">
    <div><HotelDatePicker /></div>
	
    </div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-hotel-datepicker@2.7.6/dist/vue-hotel-datepicker.min.js"></script>
    <script>
        new Vue({
               el: '#root',
            export default {
              components: {
                HotelDatePicker,
              },
            }
                 
             })
    </script>

**Comment by jefftrois60** [comment]
I changed the component name to: <hotel-date-picker> now it sees the data but nothing is showing on the screen... @matiasperrone

**Comment by jefftrois60** [comment]
<img width="996" alt="Capture d’écran, le 2020-01-28 à 14 13 57" src="https://user-images.githubusercontent.com/60400256/73296818-6e731a80-41d8-11ea-9dd1-cb71e7f61539.png">

**Comment by jefftrois60** [comment]
@matiasperrone  any hints?

**Comment by matiasperrone** [comment]
This line of questioning has nothing to do with this issue, is a javascript issue and how do you implement the dependencies?

You must request all the dependencies before this one (I think there are many +500)
So you will notice that lots of script tags must be added.

Alternative solution:
If you have a compiled version with of all the necessary files in one or two (via vue-cli build) you can upload this files (js and css) to github and the request from there...

But very complicated and messy not to use npm, yarn or pnpm.
I hope this will be helpfull for you,
