### ISSUE TITLE
Simplifying the output date

### ISSUE THREAD

**Issue by DubuBoing** [krystalcampioni/vue-hotel-datepicker#182]
Hello, is there a way for the output to be only the date? Since it's like this when I console.log it:
![image](https://user-images.githubusercontent.com/57252283/73023603-d935f600-3e66-11ea-87ed-eb4162081f2f.png)
Here's the code I used:
`<HotelDatePicker format="DD/MM/YYYY" @check-in-changed="updateCheckIn($event)" @check-out-changed="updateCheckOut($event)">
						</HotelDatePicker>`
The Script:
`export default{
components:{
			HotelDatePicker
},
data(){
			return{
				bookForm: {
					CheckInDate:'',
					CheckOutDate:'',
				},
methods:{
			},
			check(){
				console.log(this.bookForm)
			},
			updateCheckIn(date) {
                this.bookForm.CheckInDate = date;
            },
            updateCheckOut(date) {
                this.bookForm.CheckOutDate = date;
            },
		},`
Is there any way I can only make it like 

> CheckInDate:"Jan 24 2020" 
> CheckOutDate:"Jan 25 2020"

without the Day, Time, and Timezone with it?

**Comment by ayophanz** [comment]
You can format the output using moment js like ( moment(date).format('YYYY-MM-DD'); )

**Comment by DubuBoing** [comment]
Ah, that works
