### ISSUE TITLE
Datepicker only shows one month on Mobile and if you scroll down multiple times it will show next month

### ISSUE THREAD

**Issue by Santro123** [krystalcampioni/vue-hotel-datepicker#183]
### Description

Datepicker only shows one month on Mobile and if you scroll down multiple times it will show next month. Nxt and previous month button < and > are not shown.

### Steps to Reproduce

Open datepicker on mobile device or mobile layout

**Expected behavior:** User can select any month and select any next month

**Actual behavior:** Only current and next month can be chosen

### Datepicker Version

[ The version of the datepicker you have installed in your project ]

**Comment by matiasperrone** [comment]
Why did you closed this?
