### ISSUE TITLE
Unable to re-select same checkin date

### ISSUE THREAD

**Issue by alexist-ong** [krystalcampioni/vue-hotel-datepicker#184]
### Description
On the demo page [https://krystalcampioni.github.io/vue-hotel-datepicker/](https://krystalcampioni.github.io/vue-hotel-datepicker/), after user has made the first range selection, subsequently user can still re-select the same checkin date (in case if user wants to change the checkout date with the same checkin date). However, when I installed the component to my local Vue project, I could not re-select the same checkin date anymore after my first range selection. I checked and compared both the demo version and my local version, it seems to be caused by CSS rule of `pointer-events: none;` on selector `.datepicker__month-day--disabled`. Demo version doesn't have this rule.

##### app.vue
```
<template>
    <div id="app">
        <HotelDatePicker/>        
    </div>
</template>

<script>
import HotelDatePicker from 'vue-hotel-datepicker';

export default {
    components: {
        HotelDatePicker
    },
    data() {
        return {            
        };
    }
};
</script>

<style lang="scss">    
    
</style>
```

##### app.js
```
import Vue from 'vue';
import App from './app.vue';

new Vue({
    el: '#app',
    render: h => h(App)
});
```

### Steps to Reproduce
1. Select any checkin date
2. Select any checkout date
3. Now let's say I want to change only the checkout date. I re-select the same checkin date. The datepicker does not allow the re-selection

**Expected behavior:** I should be able to re-select the same checkin date, similar to the behaviour on the [demo page](https://krystalcampioni.github.io/vue-hotel-datepicker/).

**Actual behavior:** The datepicker does not allow the re-selection of same checkin date.

### Datepicker Version
2.7.7

**Comment by emad-sure** [comment]
@krystalcampioni  any help with this case , it works perfect on demo , but when installed i had the same exact issue

**Comment by matiasperrone** [comment]
I'll be trying to reproduce this error today. I'll hope have news.

**Comment by matiasperrone** [comment]
Sorry I wasn't able to check it out I didn't have the time. Please PR me or point to the problem in the code.

**Comment by alexist-ong** [comment]
Hi @matiasperrone , I believe `pointer-events: none` along the line #803 on DatePicker.vue is causing the problem. May I suggest 2 solutions to tackle this issue?

**Solution 1**
Comment out line #802 and #803 on DatePicker.vue

**Solution 2**
Add CSS rules to selector `.datepicker__month-day--first-day-selected, .datepicker__month-day--last-day-selected` to enable pointer-events. I'm proposing to have the line #820 — #824 replaced with

```
&--first-day-selected,
&--last-day-selected {
    background: $primary-color;
    color: $white;

    /* ADDING THESE 2 NEW CSS RULES */
    cursor: pointer;
    pointer-events: auto;
}
```

I personally prefer **Solution 2** as it doesn't affect any of the disabled dates. Hope it helps.

**Comment by matiasperrone** [comment]
I found the same issue on v3...

**Comment by matiasperrone** [comment]
Resolved - https://github.com/krystalcampioni/vue-hotel-datepicker/releases/tag/v2.7.8
