### ISSUE TITLE
Disable date array disable the day before

### ISSUE THREAD

**Issue by sonia360** [krystalcampioni/vue-hotel-datepicker#187]
The array
 disabledDates: ['2020-03-26', '2020-03-30'],

Disable the 2020-03-26 and 2020-03-29

If I pass disabledDates: ['2020/03/26', '2020/03/30'],
It's give me the good date.

The doc is up to date? Any Idea?

**Comment by matiasperrone** [comment]
I just found out that the docs are of an older version but, the features are similar.
I didn't understand the problem or your example is incorrect in same way.

**Comment by sonia360** [comment]
The array
disabledDates: ['2020-03-26', '2020-03-30'],

**Disable the 2020-03-25 and 2020-03-29**

If I pass disabledDates like this: ['2020/03/26', '2020/03/30'],
It's give me the good date.

but in the doc It's like my first exemple

**Comment by matiasperrone** [comment]
What do you mean with "_It's give me the good date._"?
