### ISSUE TITLE
Check disabled dates whithin the range.

### ISSUE THREAD

**Issue by sonia360** [krystalcampioni/vue-hotel-datepicker#188]
it's is normal? It's not suppose to enable only the next disable day after start date?

Currently it's enable all day so I can range hover a complete booking...

**Comment by matiasperrone** [comment]
@sonia360 can you elaborate a more detail example?

**Comment by sonia360** [comment]
Exemple:
disable date : june 3, june 5, june 10

If I choose june 2 it's suppose to enable checkout on june 3 only right?. but I can pass over all date it's enable checkout on all date. So a user can book on already booked date

**Comment by matiasperrone** [comment]
That's right, but check for disabled dates in between of a range is not a feature of the datepicker right now. Could be added but is not a bug, it's a missing feature if you like.

I am afraid that you are going to check this issues externally, but if you want you can provide a PR with the solution and I will tested and incorporate in the 2.x branch.

Can you do it?

**Comment by cjlaborde** [comment]
I encounter the same issue just now and working to see what I can do to resolve this now.

**Comment by matiasperrone** [comment]
Check v4.0.0-beta.2
