### ISSUE TITLE
Is it possible to disable all past dates from a specific date?

### ISSUE THREAD

**Issue by akation** [krystalcampioni/vue-hotel-datepicker#189]
Hello again,

I'd like to disable all past dates from a specific date, for example: I have two separated fields, one for start date and one for end date (the client wants it this way...) when the user select te start date I want to disable all past dates based on that specific start date in the end date field. Is this posible? I mean, I know i can fill an array with the dates i want to disable, but I don't want to created a script for that.

**Comment by matiasperrone** [comment]
Hi Andrés (@akation),

It's possible, check https://krystalcampioni.github.io/vue-hotel-datepicker/#moreExamples.
You have to use `startDate` prop, instead of using the disabled dates array.

**Comment by akation** [comment]
Makes sense, thank you Matias.
