### ISSUE TITLE
Exact Nights Value to perform Calculations.

### ISSUE THREAD

**Issue by cjlaborde** [krystalcampioni/vue-hotel-datepicker#191]
I would like to extract nights to perform calculations.
price * Number of Nights =  Total Cost.

Displaying nights is Great but would be better if we could extract it to perform preview of the total cost.

Or is this already possible?

**Comment by matiasperrone** [comment]
This is a Feature Request. I don't think I'll be implementing this, but I will if you can provide a PR. What do you think?

**Comment by cjlaborde** [comment]
I already resolved it weeks ago with

```js
       getNights() {
              return moment(this.end_date).diff(moment(this.start_date), 'days');
            },
```

**Comment by matiasperrone** [comment]
There is a PR?
