### ISSUE TITLE
Minimum Nights not working

### ISSUE THREAD

**Issue by cjlaborde** [krystalcampioni/vue-hotel-datepicker#193]
```js
<HotelDatePicker
 :minNights="1">
</HotelDatePicker>
```
Can Still make reservations. 
Even when 0 nights and having same date as start_date and end_date.

Here is a gif image.
https://gph.is/g/E1nMW32

**Comment by matiasperrone** [comment]
Check the last version, I couldn't duplicate this behaivour.
