### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by jpoiron** [krystalcampioni/vue-hotel-datepicker#196]
I'm getting an error when rendering and I'm wondering if perhaps I'm doing something wrong. I'd really love to use this component as it looks great!

Please see this example that reproduces the behavior. I just followed the steps in the docs to import, register, and use the component (in `HelloWorld.vue`).

https://codesandbox.io/s/heuristic-shape-w3qtn

**Expected behavior:** The component is displayed

**Actual behavior:** The component is not displayed :)

### Datepicker Version
3.0.5

**Comment by matiasperrone** [comment]
@jpoiron I am going to solve this issue between today and tomorrow.

**Comment by jpoiron** [comment]
That would be awesome, thanks!

**Comment by matiasperrone** [comment]
I have some personal issues so I am delayed

**Comment by jpoiron** [comment]
No worries, take care.

**Comment by matiasperrone** [comment]
Resolved on v3.0.7 error on build (not a UMD) and the CSS was not inline.

**Comment by matiasperrone** [comment]
Sorry still does not work

**Comment by matiasperrone** [comment]
Solved!
https://github.com/krystalcampioni/vue-hotel-datepicker/releases/tag/v3.0.9

**Comment by jpoiron** [comment]
Looks good in my codesandbox used to repro the issue. Thanks!
