### ISSUE TITLE
valid date is gray instead of black

### ISSUE THREAD

**Issue by mariusa** [krystalcampioni/vue-hotel-datepicker#198]
Hi,

In 2.x, the dates list is quite clearly differentiated. Valid dates are black:
![Screenshot from 2020-05-28 15-46-58](https://user-images.githubusercontent.com/1283842/83143449-a6dd2380-a0fa-11ea-89a1-ab8d24625e4c.png)

In current 3.0.9, valid dates are gray, which makes them harder to see:
![Screenshot from 2020-05-28 15-46-51](https://user-images.githubusercontent.com/1283842/83143479-b0ff2200-a0fa-11ea-9923-472ab56a6746.png)

https://github.com/krystalcampioni/vue-hotel-datepicker/blob/6719f973adacb8ff2d2b03abc0aa923867b7371d/src/assets/scss/main.scss#L256

Would you please change back to black? 

Also, why are the styles repeated on every cell? This decreases performance (larger DOM).
Having the colors defined in classes works fine, there's no need for `style`:
![Screenshot from 2020-05-28 15-46-44](https://user-images.githubusercontent.com/1283842/83143638-ee63af80-a0fa-11ea-835e-d59a19389904.png)

The demo is good (black and no `style`), but can't tell what version is there:
https://krystalcampioni.github.io/vue-hotel-datepicker/

**Comment by mariusa** [comment]
ping @matiasperrone ?

**Comment by matiasperrone** [comment]
I am thinking that taking the css in an external file will be the best way to go. But is a sort of breaking change so...
Anyway I'll be implementing this changes in v4 (soon...)

**Comment by matiasperrone** [comment]
Solved in v4.0.0-beta.2
