### ISSUE TITLE
Can't render plugin

### ISSUE THREAD

**Issue by xoco70** [krystalcampioni/vue-hotel-datepicker#20]
Hi, 

I'm a bit new to Front end dev. I tried to use you plugin in my project, but it doesn't render, and in debugger, vue is not detecting it.

I installed it with npm with no problem.

Then, in my boostrap.js ( this is where I declare all global components ) , I do :  

```
import HotelDatePicker from 'vue-hotel-datepicker'

export default {
    components: {
        HotelDatePicker,
    },
}
```

and then in my HTML, I insert 

                        <DatePicker DatePickerID="01"/>

I also ran `npm run dev` to run webpack, but it is not rendering... 

In the source, I can see that webpack does include the vanilla js code corresponding to the inclusion of library: 

```
import HotelDatePicker from 'vue-hotel-datepicker'

export default {
    components: {
        HotelDatePicker,
    },
}
```

Help!!! What am I doing wrong?

**Comment by lucasjahn** [comment]
hey @xoco70 

these lines 
```
export default {
    components: {
        HotelDatePicker,
    },
}
```

are actually this:
```
export default {
    components: {
        HotelDatePicker: HotelDatePicker,
    },
}
```

so if you want to use this component then you have to name it like defined in your components objects:
```
<HotelDatePicker />
```

**Comment by xoco70** [comment]
Sorry for that. I actually changed it in code, because it was not rendering. Now, I reverted it to  < HotelDatePicker /> but it stills doesn't render. No error, nothing, just doesn't show.

**Comment by lucasjahn** [comment]
Maybe you could delete your node modules directory, reinstalling everything, run your build again and check it again? 

you should also check that your import line is as follows:
`import HotelDatePicker from 'vue-hotel-datepicker'`

**Comment by lucasjahn** [comment]
Basically you just have to follow the installation instructions here: https://github.com/krystalcampioni/vue-hotel-datepicker#installation this should work right away ;)

**Comment by xoco70** [comment]
Basically, I checked the import is OK, I will do it like you said.

And also. I followed the docs, but I guess there is something I am not doing well.

**Comment by lucasjahn** [comment]
If you still have problems maybe you just could post your content of the bootstrap.js, maybe there is something still not in the correct way :) Open to help

**Comment by xoco70** [comment]
I will try to install it on a fresh copy of Laravel, so it is easier. ( I'm better in backend :)

**Comment by xoco70** [comment]
oo, don't I need a root selector? like <div id="app> ???

**Comment by lucasjahn** [comment]
Yes, of course, :D So you need a instantiated vue environment:

```
import Vue from 'vue'
import HotelDatePicker from 'vue-hotel-datepicker'

new Vue({
  el: '#app',
  template: '<HotelDatePicker />',
  components: { HotelDatePicker }
})
```

so you defenitely need a vue instance

**Comment by xoco70** [comment]
Ok! I could make it work in a fresh laravel! I think it makes sense now! Thanks for helping! For the record, I will use your plugin for my tournament app: https://kendozone.com 

Good night from Paris!
