### ISSUE TITLE
Why is the previous date blocked after selecting check-in?

### ISSUE THREAD

**Issue by cr-lgl** [krystalcampioni/vue-hotel-datepicker#201]
### Description

Why is the previous date blocked after selecting check-in?

Personally, I don't think it's very good for the user experience.

After selecting check-in, if select the previous date, I want to re-selection the check-in.

### Code sample 
https://pkgtour.naver.com/

Initial value selection:
![Jun-05-2020 15-56-32](https://user-images.githubusercontent.com/32331576/83846195-30b56e00-a745-11ea-8a08-e6f22d8db757.gif)

On re-selection:
![Jun-05-2020 16-00-55](https://user-images.githubusercontent.com/32331576/83846773-16c85b00-a746-11ea-99c3-2c01554b96a9.gif)

[Here](https://github.com/cherryred5959/vue-hotel-datepicker/tree/feature/re-selection-check-in), I simply implemented an example that meets my requirements.

I'd like to hear your opinion on this proposal.

[ v2.7.7 ]

**Comment by matiasperrone** [comment]
Do you have a PR?

**Comment by cherryred5959** [comment]
@matiasperrone No, not yet. 

I found a small problem, fix it, and then I'll post it.

**Comment by matiasperrone** [comment]
Check v4.0.0-beta.2
