### ISSUE TITLE
Icons are not loading since 3.x

### ISSUE THREAD

**Issue by guillaumebriday** [krystalcampioni/vue-hotel-datepicker#206]
### Description

In version greater than 3.x icon are missing with Webpack.
And everything works fine in <2.7.x

I think the way this library is bundled is broken. :/

[This component](https://github.com/krystalcampioni/vue-hotel-datepicker/blob/main/vue.config.js#L8) does not exist.

**Expected behavior:** [What you expected to happen]

Here's a screenshot in 2.7.8
![Screenshot 2020-06-18 at 15 13 51](https://user-images.githubusercontent.com/8252238/85025859-34e77f80-b178-11ea-824c-51ff46e4e4e0.png)

**Actual behavior:** [What actually happened]

Screenshots in 3.x
![Screenshot 2020-06-18 at 15 23 41](https://user-images.githubusercontent.com/8252238/85025887-403aab00-b178-11ea-8bc4-ec8ac3513cdb.png)
![Screenshot 2020-06-18 at 15 23 49](https://user-images.githubusercontent.com/8252238/85025888-40d34180-b178-11ea-8b5a-dbe6d6ff7830.png)

### Datepicker Version

3.x

**Comment by matiasperrone** [comment]
Can you specify the version that are you using?

**Comment by guillaumebriday** [comment]
@matiasperrone 3.0.10

**Comment by mariusa** [comment]
ping

**Comment by matiasperrone** [comment]
I haven't had the time yet, you can, if you want send a PR, maybe?

**Comment by ShapesGraphicStudio** [comment]
Hi, has this been fixed?
I seem to have the same issue.

**Comment by matiasperrone** [comment]
Not yet sorry

**Comment by matiasperrone** [comment]
Solved in v4.0.0-beta.2
