### ISSUE TITLE
Load date range based on url variables 

### ISSUE THREAD

**Issue by remcoz** [krystalcampioni/vue-hotel-datepicker#210]
Hi, 

use v3.0.10

From our listing user search on available dates, with this links pointing to the accommodations. 

domain/accommodation-1234?adults=2&check_in=2020-07-04&check_out=2020-07-11&children=&infants=
domain/accommodation-678?adults=2&check_in=2020-07-04&check_out=2020-07-11&children=&infants=
ect

On the accommodation page i want to load automatically the date in range in the calendar based on the variables check_in and check_out.  

Cannot found this in docs.  Can somebody help ?  thanks

**Comment by matiasperrone** [comment]
This seems more like a Vue issue or question.
Check `$route.query.check_out` and  `$route.query.check_in`.

You must have VueRouter installed in order to do that

**Comment by remcoz** [comment]
thanks !
