### ISSUE TITLE
Multiple options/props per calendar for minimalStay and checkinDay 

### ISSUE THREAD

**Issue by remcoz** [krystalcampioni/vue-hotel-datepicker#212]
Hi, 

We have accommodation X.  This accommodation has this rules.  

```
**Start Date | End Date | Minimum Stay | Checkin Day | Flexible Arrival**
27 juni 2020 | 21 augustus 2020 | [7, 14, 21] | saturday | 
27 juni 2020 | 21 augustus 2020 | [7, 14, 21] | saturday | 
22 augustus 2020 | 4 september 2020 | [7 ] | any | yes
5 september 2020 | 25 september 2020 | [7 ] | any | yes
1 juni 2021 | 12 juni 2021| [7 ] | any | yes
11 juni 2021 | 24 juni 2021 | [7 ] | any | yes
```

So we have per date range different minimalstay and checkin day (saterday or any). 

![multiple](https://user-images.githubusercontent.com/33696/86124793-f8067b80-badb-11ea-9211-6af591ebaf19.jpg)

Is this possible in the plugin? 

best, remco

**Comment by matiasperrone** [comment]
Is not possible in the plugin, but you can use computed properties in order to solve this particular issue.
