### ISSUE TITLE
Cannot use back button for past months

### ISSUE THREAD

**Issue by Gadurp1** [krystalcampioni/vue-hotel-datepicker#22]
I have my startDate set to the beginning of the year.  I am unable to hit the back button in the calendar popup so and am locked on current month.

**Comment by krystalcampioni** [comment]
@Gadurp1 v2.0.7 is now using the startDate to mount the datepicker.

A nice functionality to put in the roadmap -  that relates to this - is allowing the user to select the default date for when we open the datepicker ( maybe the current month? ) Feel free to submit a PR if you would like to contribute.
