### ISSUE TITLE
Selected and disabled date are not showing up in v2.x

### ISSUE THREAD

**Issue by guillaumebriday** [krystalcampioni/vue-hotel-datepicker#223]
### Description

When dates are selected but in a disabled range there are just disabled for the user.

For instance,

When there is no disabled dates:
![Screenshot 2020-09-08 at 18 03 33](https://user-images.githubusercontent.com/8252238/92501297-a591bb80-f1fe-11ea-8f22-1f5b4af5e61a.png)

When only saturdays are enabled:
![Screenshot 2020-09-08 at 18 03 46](https://user-images.githubusercontent.com/8252238/92501340-b04c5080-f1fe-11ea-88d3-32da0d1eed48.png)

### Code sample 
I think it's related to this computed method:

https://github.com/krystalcampioni/vue-hotel-datepicker/blob/main/src/components/Day.vue#L121

Will open to simplify this method.

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

We should be able to see selected days in disabled range.

**Actual behavior:** [What actually happened]

We can't.

### Datepicker Version
Latest.

**Comment by matiasperrone** [comment]
Are you using the v4 beta version?

**Comment by guillaumebriday** [comment]
Nope still 2.7.8 because can't upgrade to 3.x https://github.com/krystalcampioni/vue-hotel-datepicker/issues/206 and 4 is in beta

**Comment by matiasperrone** [comment]
I'll try today to update the 3.x version, but thw 2.x it is old, and very deprecated, tons of security issues.

**Comment by guillaumebriday** [comment]
Ok I will try to upgrade to the latest stable soon!

**Comment by superbiche** [comment]
Closing to focus efforts towards v4.0
