### ISSUE TITLE
css file not loading from .vue file

### ISSUE THREAD

**Issue by danMoses10** [krystalcampioni/vue-hotel-datepicker#228]
my single file component contains the vue-hotel-datepicker, I can initialise the datepicker, but the css doesn't take effect.

html:
```vue
<vue-hotel-datepicker>
</vue-hotel-datepicker>

<script>
import 'vue-hotel-datepicker/dist/vueHotelDatepicker.css'; ------------
import VueHotelDatepicker from 'vue-hotel-datepicker' --------------


export default {
  components: {
    'vue-hotel-datepicker': VueHotelDatepicker,
    'add-guests-picker': AddGuestsPicker,
    'month-picker': VueMonthlyPicker,
}}
</script>
```

**Expected behavior: datepicker to load with css styling

**Actual behavior:**datepicker loads with no styling

### Datepicker Version: ^4.0.0-beta.9

```vue
<vue-hotel-datepicker>
</vue-hotel-datepicker>

<script>
import 'vue-hotel-datepicker/dist/vueHotelDatepicker.css';
import VueHotelDatepicker from 'vue-hotel-datepicker'


export default {
  components: {
    'vue-hotel-datepicker': VueHotelDatepicker,
    'add-guests-picker': AddGuestsPicker,
    'month-picker': VueMonthlyPicker
}}
</script>
```

**Comment by matiasperrone** [comment]
@danMoses10 Hi, seems that your HTML is a little bit off.

Try this out:

```vue
<template>
    <vue-hotel-datepicker style="max-width: 400px;" />
</template>

<script>
import "vue-hotel-datepicker/dist/vueHotelDatepicker.css";
import VueHotelDatepicker from "vue-hotel-datepicker";

export default {
  name: "App",
  components: {
    VueHotelDatepicker
  }
};
</script>

```

**Comment by danMoses10** [comment]
Hi, I have tried this but it is still not loading the css, I am having to copy the scss files to my local folder for it to work, which I would rather not do

**Comment by superbiche** [comment]
@danMoses10 please provide a tarball or codesandbox of your reproducible issue and I'll have a look into it.

**Comment by danMoses10** [comment]
@superbiche it's ok man thanks, I moved onto a different datepicker

**Comment by matiasperrone** [comment]
@danMoses10 may you anyway provide us anyway with your example, to look for clues? maybe there are others with the same issue.

**Comment by mariusa** [comment]
Since no followup, I guess this can be closed.
This works for me:
```
import 'vue-hotel-datepicker/dist/vueHotelDatepicker.css'
```

**Comment by Merton** [comment]
This work around of importing the CSS directly works, but is there clarity on why this happens? Without the CSS import all the functionality / logic works but simply no styling.
For context I am using Nuxt.js (v2.14.6), and importing it the standard way as per your documentation.

Cheers

**Comment by matiasperrone** [comment]
This is not a workaround, is the best way that you may restyle it without interference.
