### ISSUE TITLE
disabledDates doesn't work

### ISSUE THREAD

**Issue by MateoArgalle** [krystalcampioni/vue-hotel-datepicker#229]
I am trying to disable the holidays in my country but it does not work, it does not have the same effect as disabling the days that is exactly what I need

![image](https://user-images.githubusercontent.com/58223373/95135033-769d3580-0729-11eb-972a-970e6010173d.png)

**Comment by matiasperrone** [comment]
@MateoArgalle you should provide us with the version, an example on how to reproduce, and any other detail that you think may help.
Probably you should follow the template.

**Comment by matiasperrone** [comment]
Closed due lack of response.
