### ISSUE TITLE
showYear should be true by default.

### ISSUE THREAD

**Issue by matiasperrone** [krystalcampioni/vue-hotel-datepicker#232]
I think that `showYear` should be true by default.... makes sense.

What do you think @superbiche, @krystalcampioni ?

**Comment by krystalcampioni** [comment]
Sure, that makes sense! Let's just make sure to release this as breaking change 👍🏽

**Comment by superbiche** [comment]
@matiasperrone yup, makes sense. Let's do this before releasing v4.0.0, we can still add some breaking changes

**Comment by matiasperrone** [comment]
Sure... what other breaking changes there will be?

**Comment by matiasperrone** [comment]
I'll go with "disabled week days", now they are harcoded with the traslation as names... we could use numbers.

**Comment by superbiche** [comment]
I agree. These should be integers or US day names. 
I'd also use objects for the day/month names instead of an array, as it's a pain when coupling with Vue-i18n and a translation system (we use Weblate).

**Comment by superbiche** [comment]
@matiasperrone I'm creating an issue for the last steps towards v4.0.0. Could you either edit your issue or create an new one with these items (add if I'm missing some) : 
- [ ] `showYear` should default to `true`  
- [ ] update docs accordingly  

I'm creating issues for the rest

**Comment by matiasperrone** [comment]
It is correct, the first is now corrected. I have found a "bug" value is never mutated... :(

**Comment by superbiche** [comment]
@matiasperrone damn... Let's make an issue of it if you will

**Comment by matiasperrone** [comment]
Solve in commit https://github.com/krystalcampioni/vue-hotel-datepicker/commit/82d3a644c6663bf668350fddd58a8e9c2788be9b
