### ISSUE TITLE
 mix and match the props/options in different months. 

### ISSUE THREAD

**Issue by remcoz** [krystalcampioni/vue-hotel-datepicker#234]
Hi,

we want  mix and match the props/options in different months.  We have accommodations that have in the summer months Ranges of 7, 10 or 14 days and checkin only on saturdays and in the spring they have  minimum 3 nights and checkin all days.  

Is this possible ? 

best...remco

**Comment by superbiche** [comment]
Hi @remcoz ,
I don't this that's possible out of the box, and while this would be a relevant feature, it is not trivial to implement.   
What *could* be done more easily is either emit events when changing month visibility, or bind a model to the current month(s) visible.   

Anyway it's not something that can be done right now but I'm tagging it as it's definitely an interesting use case.  

We'll let you know when adding a feature that could help you in this use case.  

Cheers

**Comment by matiasperrone** [comment]
I do was thinking in implement a better events emit, because today in v4 still there are some limitations.

**Comment by superbiche** [comment]
> I do was thinking in implement a better events emit, because today in v4 still there are some limitations.

Well that's great, as you say, the events are pretty limited for now. This could allow working around some custom behaviors, and leave some room to discuss more complex changes like the one @remcoz needs - I *may* need this kind of feature for one of my clients sooner or later, so maybe I'll work on it when v4 has been released.

**Comment by matiasperrone** [comment]
I was thinking on v5 with Vue v3 compatibility.
Some rewriting has to be done to better control some events.

**Comment by superbiche** [comment]
@matiasperrone I added a v4.x milestone for stuff that *could* make it during v4 but maybe *won't*. But I think this should be splitted in two issues:  
* One for the events, v4.x or v5 as you say  
* One for customizing props depending on the month, without any milestone.

**Comment by matiasperrone** [comment]
I am going to close this. `next-month-rendered` event maybe it'll be helpful.
Check the new v4.1 version.
