### ISSUE TITLE
API : Freeze the current API, only allow additions for v4 & v5

### ISSUE THREAD

**Issue by superbiche** [krystalcampioni/vue-hotel-datepicker#240]
After having a great discussion with @matiasperrone , we decided the following:  

* v4.0.0 must be released with a documented API - props & events  
* v5.0.0 will be based on a v4 backward-compatible API  
* **only absolutely necessary breaking changes will be added between v4.0 and v5.0** 

What we need to do for this:  
- [x] Make sure every prop & event is aknowledged and documented  
- [ ] Write tests to make sure these props & events don't throw any error

**Comment by matiasperrone** [comment]
I am not going to write the tests because no final version will come out. so I close this issue
