### ISSUE TITLE
Emit an event when next month is rendered

### ISSUE THREAD

**Issue by nathanjhastings** [krystalcampioni/vue-hotel-datepicker#242]
We get our availability and pricing data from an API and need to push this to the calendar based on which month the user is viewing.

To do this we have added an event when the next month has been rendered.

PR on it's way!

**Comment by matiasperrone** [comment]
Thanks!
The PR is for v3 or v4?

**Comment by nathanjhastings** [comment]
The PR was done on master but happy do this on a v4 branch. I am actually using this on a v4 branch in production.

**Comment by matiasperrone** [comment]
@nathanjhastings please do.
I am sorry, but v3 is frozen now, v4 is almost RC, but a couple of breaking changes will happen soon, check the other issues.
I'll be working in this in the next few days for v4 final release.

I'll try not to do the BC that I was talking about, but a couple of improvements will be implemented.

**Comment by matiasperrone** [comment]
done in #253
