### ISSUE TITLE
How to pre populate check in/out values

### ISSUE THREAD

**Issue by Merton** [krystalcampioni/vue-hotel-datepicker#244]
### Description
If the parent or vuex store has a previously entered values for check in and checkout, and I want to display that in the inputs / selector display, is this possible?
I was expecting there to be a prop for check in and checkout, then on update I can update the store / parent.

Cheers

**Comment by matiasperrone** [comment]
I don know if a understand, do you mean like the `startingDateValue` and `endingDateValue`?...

**Comment by Merton** [comment]
Yes absolutely I am being silly, thank you. I misunderstood that somehow..apologies! Really like the component 😄
