### ISSUE TITLE
CSS Not loaded

### ISSUE THREAD

**Issue by maghffu** [krystalcampioni/vue-hotel-datepicker#250]
### Description

Hi, I already install vue-hotel-datepicker, but when i import the plugin, css wasn't loaded

### Code sample 
<template>
  <HotelDatePicker />
</template>
<script>
import HotelDatePicker from "vue-hotel-datepicker";
export default {
  components: {
    HotelDatePicker,
  },
};
</script>

### Steps to Reproduce

1. npm install vue-hotel-datepicker --save
2. Create file and fill with code above
3. Open the page

**Expected behavior:** Vue hotel datepicker show properly

**Actual behavior:** css wasn't loaded

### Datepicker Version

4.0.0-beta.9

**Comment by matiasperrone** [comment]
Hi! did you solve the issue? Remember to import the css file :D
