### ISSUE TITLE
Disable selecting a date right after block of "disabled" dates

### ISSUE THREAD

**Issue by joelkrause** [krystalcampioni/vue-hotel-datepicker#251]
We have an interesting issue a client has faced on their website using this. We're passing in an array of disabled dates, and they would like the ability to prevent a customer from selecting the date right after that block? Is there any way to achieve this?

**Comment by matiasperrone** [comment]
You may add a day to each block... or may be I did not understand the problem right

**Comment by matiasperrone** [comment]
This seems to be a duplicate of #252 please continue in that issue
