### ISSUE TITLE
Disabled days problem

### ISSUE THREAD

**Issue by yashiroiori** [krystalcampioni/vue-hotel-datepicker#252]
Hi.
How I make to disable all day??
The events get from Google Calendar

In image set disabled days: 2021-01-02, 2021-01-03, 2021-01-04 but in image only block day: 2021-01-02 and it's available to select 3 and 4 day but it's not correct can't choose day 3 and 4

![image](https://user-images.githubusercontent.com/17031855/102157329-e5db8800-3e44-11eb-9a7e-c17725b2797c.png)

If set true halfDay block date 2021-01-01 automatic, why it's block??

![image](https://user-images.githubusercontent.com/17031855/102157965-0f48e380-3e46-11eb-9616-834a524fe70d.png)

**Comment by matiasperrone** [comment]
What version are you using?
- vue-hotel-datepicker Package
- SO
- Browser

Please provide me with a working example and indicate your local time zone.

**Comment by yashiroiori** [comment]
> What version are you using?
> 
> * vue-hotel-datepicker Package
> * SO
> * Browser
> 
> Please provide me with a working example and indicate your local time zone.

Chrome

**Comment by matiasperrone** [comment]
And the versions of those?
Which version of this package are you using?

**Comment by matiasperrone** [comment]
Ahhh and don't forget to tell me you local time zone.

**Comment by yashiroiori** [comment]
> Ahhh and don't forget to tell me you local time zone.

Version: "vue-hotel-datepicker": "^4.0.0-beta.9"
Time zone: America/Mexico_City

Another thing it's in this case, when set :firstDayOfWeek="1" the days move but at the top days not move, for example Thursday it's Friday because Friday I set require min 2 nights

![image](https://user-images.githubusercontent.com/17031855/102231972-34743b00-3eb4-11eb-941b-d6c33bdaa6e5.png)

**Comment by matiasperrone** [comment]
Thanks!

Can you provide me with an Vue example of the code? 
Maybe an unique Vue component file with your configuration hardcoded in `data` in order to be able to reproduce it?

**Comment by yashiroiori** [comment]
> Thanks!
> 
> Can you provide me with an Vue example of the code?
> Maybe an unique Vue component file with your configuration hardcoded in `data` in order to be able to reproduce it?

Component:
<HotelDatePicker
    :i18n="i18n"
    :firstDayOfWeek="1"
    :showYear="true"
    :showPrice="true"
    :halfDay="false"
    :periodDates="periodDates"
    :disabledDates="disabledDates"
    :lastDateAvailable="new Date(moment().add(6, 'M').format('YYYY-MM-DD'))"
/>

disabledDates:Array[3]
0:"2021-01-02"
1:"2021-01-03"
2:"2021-01-04"

**Comment by yashiroiori** [comment]
Find into the demo the same bug

Url demo https://github.com/krystalcampioni/vue-hotel-datepicker/tree/v4.0.0-dev/src

Without halfDay
![image](https://user-images.githubusercontent.com/17031855/102822122-02744480-439e-11eb-9cda-130023f1efa3.png)

With halfDay
![image](https://user-images.githubusercontent.com/17031855/102822236-47987680-439e-11eb-96d8-a91bf190f1fd.png)


![image](https://user-images.githubusercontent.com/17031855/102822144-15871480-439e-11eb-8930-08ce76dafc12.png)

**Comment by matiasperrone** [comment]
Check the last version please... did you notice a change?

**Comment by matiasperrone** [comment]
I will check this issue before release the next beta (The next is 14)

**Comment by yashiroiori** [comment]
> Check the last version please... did you notice a change?

Hi.

Update de package using: "vue-hotel-datepicker": "^4.0.0-beta.13" but have a problem not find file "vueHotelDatepicker.css"

I check in dist folder not exists
![image](https://user-images.githubusercontent.com/17031855/103181751-4d90ca80-486a-11eb-9bba-f04769d439af.png)

**Comment by matiasperrone** [comment]
Check that now! Sorry for the inconvinience

**Comment by matiasperrone** [comment]
I solve the extra day, but not the first. I think this issue is related to local timezone. I am conducting some tests

**Comment by yashiroiori** [comment]
Excelent good job thank very much
