### ISSUE TITLE
Could you please release 4.0.0-beta.10 on npm? 

### ISSUE THREAD

**Issue by guillaumebriday** [krystalcampioni/vue-hotel-datepicker#254]
### Description

Hey 👋 

I see a tag `v4.0.0-beta.10` on Github but it does not seem to be release on NPM? https://www.npmjs.com/package/vue-hotel-datepicker

I need it to try something, could you please build and release it?

Thanks 🙏

**Comment by matiasperrone** [comment]
Done!

**Comment by guillaumebriday** [comment]
Thanks!! @matiasperrone
