### ISSUE TITLE
How to Show date now instead start date?

### ISSUE THREAD

**Issue by maghffu** [krystalcampioni/vue-hotel-datepicker#260]
### Description

How to show date now? my date picker always show the start date. if I set start date now, date before the 'start date' will be disabled.

### Code sample 
```vue
<HotelDatePicker startDate="2020-01-01"></HotelDatePicker>
```

### Steps to Reproduce

1. start with code above.
2. i want to show date now
3. if i fill the start date with date now, date before will be disabled

**Expected behavior:** i want to show date now

**Actual behavior:** show date in start date

### Datepicker Version: 

v3

**Comment by matiasperrone** [comment]
You should use the "startingDateValue" prop for showing and "startDate" and "endDate" for availability.

Please try v4 that has a lot of improvements. v3 is frozen and not maintained any more.
Tell us if my solution worked for you!
