### ISSUE TITLE
How to enable old dates?

### ISSUE THREAD

**Issue by akation** [krystalcampioni/vue-hotel-datepicker#263]
**Describe the bug**
I have been using this plugin for a year, but now I have a different scope that I would like to fulfill with this plugin.

I know this plugin was created to work with hotel/reservations logic, but I want to apply a different scope in my app, so I want my users to select old dates, how can I do it? I tried doing something like this:

`:show-year="true"
                  start-date="01/01/2020"`

But when I try to hit the back button (so I can see older months than the current month) it does not work.

**Comment by matiasperrone** [comment]
I am assuming that you are using the last v4.1 version.
The `startDate` is the first available date not the selected date. To use the selected date you have to use the `startingDateValue` and `endingDateValue`, `startDate` should be `1900-01-01` or maybe  `new Date(1990, 0, 1, 0, 0, 0, 0)`.

It was helpful?

**Comment by akation** [comment]
> I am assuming that you are using the last v4.1 version.
> The `startDate` is the first available date not the selected date. To use the selected date you have to use the `startingDateValue` and `endingDateValue`, `startDate` should be `1900-01-01` or maybe `new Date(1990, 0, 1, 0, 0, 0, 0)`.
> 
> It was helpful?

I am using 2.7.8, the project is working properly, can I make it work with that older version?

**Comment by akation** [comment]
I remember once I used the current version (months ago) but there was a bug so I had to rollback to 2.7.8.

**Comment by matiasperrone** [comment]
You should check the new version. But also check the documentation.

**Comment by matiasperrone** [comment]
I am not familiarized with that version. maybe @krystalcampioni may help you.

**Comment by matiasperrone** [comment]
Note that the CSS is in a different file and all the bugs has been fixed.
