### ISSUE TITLE
Price styling

### ISSUE THREAD

**Issue by maaqib121** [krystalcampioni/vue-hotel-datepicker#264]
**Description**
When we add prices to the component, the price of a date is shown on the top of dates beneath that, instead of showing in that date's box. Also, the disabled dates are not working properly. On the first attempt, all the disabled dates are available to select instead of not allowing us to select them.

**To Reproduce**
1. Go to Sandbox link
2. Check that the prices of dates are shown on the top of dates beneath them.
3. 21, 22, 23 Jan 2021 dates are disabled, but this functionality is also not working properly

**Expected behavior**
1) The price should show in the same slot where the date is.
2) Disabled dates should not be available to select even on the first attempt.

**Sandbox Link**
https://codesandbox.io/s/pedantic-wright-qq6d3?file=/src/App.vue

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 88.0.4324.96 (Official Build) (x86_64)

**Comment by matiasperrone** [comment]
The problem with disabledDates is a known issue.
I will look the problem with the position of the price as soon as I can, but it may take one or two weeks.

An update in the main branch was made in order to be able to change dynamically such prop. See #257.

Is this something that can be solved using CSS?

**Comment by matiasperrone** [comment]
In v4.2 is now fixed the disabledDates issue.
I will look into this in the following weeks.

**Comment by maaqib121** [comment]
Sure, thanks. I will check it out the v4.2

**Comment by nathanjhastings** [comment]
We wanted the price at the bottom of the square too so we added the below css.

`.vhd__datepicker__wrapper .vhd__datepicker__month-day-wrapper strong {
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%);
}`

**Comment by matiasperrone** [comment]
@nathanjhastings Check the live coding! https://codesandbox.io/live/94w9xvl

**Comment by nathanjhastings** [comment]
@matiasperrone added that code in that example

**Comment by matiasperrone** [comment]
Hi! Now I am working on solving this issue... it seems a little more complicated than appears to be
