### ISSUE TITLE
One table display

### ISSUE THREAD

**Issue by jmaric** [krystalcampioni/vue-hotel-datepicker#271]
it would be good if you could display only one table(one month), instead of 2

also it would be nice if it could open to the left and right side... now it's opening just on the right, and it breaks pages grid...

**Comment by matiasperrone** [comment]
That It is possible since version 3. We are working on the open up or down feature

**Comment by matiasperrone** [comment]
Sorry about the demo page, it is not updated... actually it is using the v2

**Comment by jmaric** [comment]
Oh great, where can i see new features?

**Comment by matiasperrone** [comment]
Right now? downloading the source and running "npm i" and then "npm run serve"

**Comment by matiasperrone** [comment]
`showSingleMonth` true solves the request.
