### ISSUE TITLE
Different Check-in/Check-out Days in different periods

### ISSUE THREAD

**Issue by maaqib121** [krystalcampioni/vue-hotel-datepicker#272]
**Is your feature request related to a problem? Please describe.**
In the documentation of some previous version, I saw there was an option of setting specific week days e.g. Monday, Tuesday etc. as check-in and check-out days. It worked fine, if you have same check-in and check-out days for the whole period. But what, if we want to set different check-in and check-out days in different periods as it is very common in holiday rental business.

**Example 1:**
Period: March 01 -> March 20:
Check-in days: Mon, Tue & Wed
Check-out days: All
**Expected Behavior:** Do not allow checkin on any other week days, except Mon, Tue & Wed during Match 01 to March 20.

**Example 2:**
Period: March 21 -> March 31:
Check-in days: Fri, Sat & Sun
Check-out days: Weekdays
**Expected Behavior:** Do not allow checkin on any other week days, except Fri, Sat & Sun and allow check out only on week days (Mon, Tue, Wed, Thu, Fri) during Match 21 to March 30.

**Describe the solution you'd like**
Currently, we are setting the prices and minimum nights for a specific period in periodDates prop. What if we can get the support to set the check-in and check-out days in periodDates prop as well, so that we can set different check-in and check-out days for different periods as well.

**Comment by maaqib121** [comment]
Updated the question with a bit more clarity in examples and their expected behaviors.

**Comment by matiasperrone** [comment]
Ok I will check it out soon

**Comment by remcoz** [comment]
Yes we also looking for the same UX behavior.  In the private holiday rental is this very common. Wil be great if this new enhancement wil be added!

**Comment by matiasperrone** [comment]
Well this is an interesting behavior, it seem rather specific.
Did you tried to control it using events?

The docs in this URL: https://krystalcampioni.github.io/vue-hotel-datepicker/ are in v2... and v4 has the same features as v2 and v3 and I am not seeing the way of doing this.

The only way that I see of handling this exact behavior is doing it in a event or in a computed property that changes the `disabledWeekDays` prop when some checkin date is selected.

**Comment by matiasperrone** [comment]
I wasn't able to develop this feature yet. 
A PR is welcome if @maaqib121 or @remcoz want to send it to us.
