### ISSUE TITLE
Price format

### ISSUE THREAD

**Issue by nathanjhastings** [krystalcampioni/vue-hotel-datepicker#274]
There was recently a change to the price format to use a number rather than a string. This works fine but it's causing an issue for us on mobile to fit the cost of stay in the space we have e.g. £423.00. This was not an issue before as we passed the string £435 as there is no need to pass the zero pence.

Would it be possible for us to implement the option of passing the price in a string format?

Happy to write a pull request if we can agree a solution.

**Comment by matiasperrone** [comment]
Price is in effect a String. Check the `src/DatePicker/components/Price.vue` component, but it is formated that way. Please PR with incorporation of a priceDecimals and the doc and I will implement that.

Line 187 of `Day.vue`

**Comment by matiasperrone** [comment]
Well already finished this... I am testing now

**Comment by nathanjhastings** [comment]
Great! What branch is this in?

**Comment by matiasperrone** [comment]
v4.4 but I will try to release a beta version in the next hours

**Comment by matiasperrone** [comment]
Sorry I've been extremely busy.

**Comment by matiasperrone** [comment]
sorry not ready yet

**Comment by matiasperrone** [comment]
v4.4.2 should fix this issue with the new props
