### ISSUE TITLE
No event when previous months rendered.

### ISSUE THREAD

**Issue by maaqib121** [krystalcampioni/vue-hotel-datepicker#277]
**Is your feature request related to a problem? Please describe.**

**Scenario**
Suppose we are month-wise populating prices in the calendar using API. Let's say, the initial selected date is May 08, 2021, so initially prices for the whole May month will be loaded in the calendar. When we click on 'Next Arrow', there is an event 'next-month-rendered' which gets triggered for every 'untraversed' month and it can be used to make an API call and load prices for the next months (June, July, Aug and so on in our case) as well.

**Issue**
There is no such event if we want to have the similar behavior to load prices for previous months.

**Describe the solution you'd like**
An event most probably **previous-month-rendered** which should trigger when we click on the previous arrow.

**Comment by matiasperrone** [comment]
Those (previous) months were already visited?

**Comment by maaqib121** [comment]
No, they ain't visited, and even we visits them, there is no event which we can trigger for them.

**Comment by remcoz** [comment]
is this bug going to be fixed in new release?  For us its important also...thanks

**Comment by maaqib121** [comment]
This feature is kind of urgent for me as well. I will be highly grateful, if any collaborator can give me an idea of how much time can it take to be implemented.

**Comment by matiasperrone** [comment]
If you please provide me with an PR, I will update the version with you solution!

**Comment by matiasperrone** [comment]
@maaqib121 what about that PR?

**Comment by maaqib121** [comment]
@matiasperrone  sorry for responding very late. I had been extremely busy lately, but now-a-days got some time to add this feature along with a couple of fixes. Will try to provide you with a PR very soon with my solution.

**Comment by matiasperrone** [comment]
Thanks! I am busy too... that's why I didn't have the time.

**Comment by matiasperrone** [comment]
done on v4.5
