### ISSUE TITLE
Close icon does not load

### ISSUE THREAD

**Issue by amr-coding** [krystalcampioni/vue-hotel-datepicker#281]
**Describe the bug**
After installing the package and importing it, everything seems to work but the icons is not working.

I checked the computed styles on my browser I found the background styles that contains the svg icons path, I hovered over the path of the svg icon and it shows "Could not load the image". 

The path looks like this: http://localhost:8000/images/vendor/vue-hotel-datepicker/dist/ic-arrow-right-datepicker.regular.99ab0620.svg?38d376a780635ae10e835c1c1a66cac8

I'm currently using Laravel with Vue.js for development 

**To Reproduce**
1. Go to 'the date-picker input'
2. Click on the input field 
3. Icons can't be loaded and that is the error

**Expected behavior**
The package icons should be loaded in the date picker.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/47779157/115995764-d29fac80-a5dc-11eb-92d4-fa81276442fe.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, firefox]
 - Version [89.0b2 (64-bit)]

**Comment by matiasperrone** [comment]
Whet version are you using??

**Comment by erenergul** [comment]
Same for me as well. I installed today latest version v4.3
fonts/vendor/vue-hotel-datepicker/dist/img/ic-arrow-right-green.regular.83ed3b6c.svg?83ed3b6cd733b2b6d8fcf86389fbbbc9 404 (Not Found)
This is my console error.

**Comment by matiasperrone** [comment]
Please try the last version (v4.4)

**Comment by erenergul** [comment]
Im sorry but it looks last version v4.3 - I couldn't see v4.4.

**Comment by matiasperrone** [comment]
Version v4.4 is now available!

**Comment by qayumhasan** [comment]
not working. i install "vue-hotel-datepicker": "^4.4.0", but Icons can't be loaded

**Comment by qayumhasan** [comment]
may be icons path can not found if project load from subfolder

**Comment by matiasperrone** [comment]
Thanks guys for testing... anyone of you can fix it? I can publish a new version but I am a little swamp right now in my paid work. I promise to fix it soon... probably during the weekend.

**Comment by amr-coding** [comment]
> Thanks guys for testing... anyone of you can fix it? I can publish a new version but I am a little swamp right now in my paid work. I promise to fix it soon... probably during the weekend.

Thanks for your efforts,
As I'm using Laravel the assets is required to be in the folder Public, so I moved the package assets to the Public folder and by doing that it worked just fine.

Usually when I install any package in any of my projects, I don't move any of the assets from the packages folders to the Public folder, so it's just in this case I encounter this problem and the only solution I could make is to move the assets from the package /src folder to the Laravel /public folder.

Anyways, I appreciate your efforts for building hotel date picker with such a great design.

**Comment by develth** [comment]
Hi,

seems like the mentioned icons work. 
But i recognized, that the lcose icon is missing (404). Regardless of the svg in Project doesn´t shows anything

**Comment by matiasperrone** [comment]
They are not been packed by webpack... do you how to fix this? please PR if you can.

**Comment by matiasperrone** [comment]
A new version was pushed v4.4.2 please try again and let me know

**Comment by seking01** [comment]
this is still not fixed in v4.4.2. Close X is still missing

**Comment by matiasperrone** [comment]
Can you PR us with the fix? or some way of testing this... because I don't have much to fix it

**Comment by matiasperrone** [comment]
@develth and/or @insek, if you want you can PR the solution. I don't have the time right now to fix it.

**Comment by austinziza** [comment]
any solution yet for this error, it is displaying an x button but cant load the image

**Comment by matiasperrone** [comment]
Not yet, A Pull Request is welcome!

**Comment by austinziza** [comment]
i noticed the close.ac44076c.svg in the dist folder is corrupt, do you have a copy of the close.svg
