### ISSUE TITLE
found only show close symptom "x", but can't show image

### ISSUE THREAD

**Issue by newbie2005** [krystalcampioni/vue-hotel-datepicker#295]
Can't show image as below
![image](https://user-images.githubusercontent.com/9400951/126148346-228116c8-b726-4364-ab3a-a349533681df.png)

**Comment by develth** [comment]
Issue with resolve. I also have:

> GET http://localhost:3000/assets/img/close.ac44076c.svg 404 (Not Found)

**Comment by matiasperrone** [comment]
@develth Version that you are using? some other info?

**Comment by develth** [comment]
@matiasperrone the current 4.4.2. 
But it also wasn´t found in the Version before

**Comment by insek** [comment]
I'm having same issue with 4.4.2 
close.ac44076c.svg 404 (Not Found)

However I'm using this with Nuxt.

**Comment by develth** [comment]
Using nuxt, too.
Seems like `@asset`does not update / trigger. It´s the only file that is included with this.
Maybe fix it with an optimized inline svg (e.g. with https://jakearchibald.github.io/svgomg/ )?

**Comment by matiasperrone** [comment]
This is a duplicate of #281 please refer to that issue

**Comment by matiasperrone** [comment]
@develth and/or @insek, if you want you can PR the solution. I don't have the time right now to fix it. Any comments please refer to comment on #281
