### ISSUE TITLE
Max nights don't work

### ISSUE THREAD

**Issue by Saganic** [krystalcampioni/vue-hotel-datepicker#296]
**Describe the bug**
Max nights prop doesn't work.

**To Reproduce**
1. Create a new project. 
2. Import the package and set up max-nights prop.
3. Click check in date, notice dates beyond 5 days aren't disabled.
4. To get it to work, click the Check in date, then click forward in the month pagination, then click back.
5. Notice that dates are now disabled.

**Expected behavior**
Click check in date, dates should be disabled beyond max-nights.

**Screenshots**
![Screenshot 2021-08-05 at 10 15 24](https://user-images.githubusercontent.com/5628286/128325170-bf7454b1-6ad4-412d-87ad-e8232968d17d.png)
![Screenshot 2021-08-05 at 10 15 55](https://user-images.githubusercontent.com/5628286/128325257-6da8d554-b1e6-4b57-a02f-7619f88916e8.png)
![Screenshot 2021-08-05 at 10 16 13](https://user-images.githubusercontent.com/5628286/128325293-e82fd7fd-c50e-4f87-9aad-12f994fcb8b9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 92.0.4515.107

**Additional context**
Seems like it could be a reactivity issue

**Comment by matiasperrone** [comment]
Hi @Saganic thanks for the report, what version are you using?

**Comment by whitewaterdesign** [comment]
https://github.com/whitewaterdesign/vue-hotel-datepicker/commit/eb1a1cf2e033d09a77871204a1ae793c82e910a4 fixes this

**Comment by whitewaterdesign** [comment]
issue is in v4.4.3
