### ISSUE TITLE
Check out date can be earlier than check in date

### ISSUE THREAD

**Issue by jeffreybrayne** [krystalcampioni/vue-hotel-datepicker#30]
Clicking around on the calendars, I can get the end date to be earlier than the start date. Is there validation to prevent this?

**Comment by Maxximus007** [comment]
Did you test with the current version? On the example page all dates before the start date do become unavailable.

**Comment by jeffreybrayne** [comment]
Yes, I've tested with the most recent. If you choose a date range, then click on the end date again and then select a previous date, it will capture it and send you back in time.

**Comment by krystalcampioni** [comment]
@jeffreybrayne could your please show us your code, and the steps to reproduce this issue?

**Comment by jeffreybrayne** [comment]
Sure. Here's my markup:
<hotel-date-picker
            id="travelDates"
            name="travelDates"
            format="MM-DD-YYYY"
            :startDate="setMin()"
            endDate="2018-05-31"
            :minNights="0"
            @checkInChanged="setDepartureDateValue"
            @checkOutChanged="setReturnDateValue"
           />

I was just fooling around with it and discovered it works fine until I add minNights="0". I've tried both binding and assigning statically and the same behavior results. To reproduce, add minNights="0" then choose a date and go backward. The prior dates are not being disabled.

**Comment by leemora** [comment]
How about a :selectForward prop to toggle this ability like in the last version?

**Comment by krystalcampioni** [comment]
@leemora  When we rewrote the component for version 2, we decided to remove the selectForward option as it added complexity to maintain the component and didn't seem good enough in terms of UX to be worth to keep it.

@jeffreybrayne please update your project to use v 2.0.11 to solve this issue.
