### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by arjanc** [krystalcampioni/vue-hotel-datepicker#305]
**Is your feature request related to a problem? Please describe.**
I wanted to overwrite the default color styles with my own colors.

**Describe the solution you'd like**
Separate index.scss file into chunks for better override of variables.
like for example `_basestyles.css`, `_settings.scss`.
Where `_settings.scss` will import the `_mixins.scss` and `_variables.scsss`. 
See this sandbox as an example: [Example](https://codesandbox.io/s/styling-the-vue-hotel-datepicker-d1okq?file=/src/components/scss/index.scss)

**Describe alternatives you've considered**
No alternative found yet.

**Additional context**
The purpose for separating the scss files for easy overwrite is to maintain the basestyling from the package itself. This will allow the package to be updated together with the base styles and to keep your own color overwrites.

**Comment by matiasperrone** [comment]
Hi @arjanc, please submit a PR to make my life easier... if not it might take me some time to make the changes, I've been away from VueJS this past few months.

**Comment by matiasperrone** [comment]
@arjanc I think the last version does what you requested.
