### ISSUE TITLE
minNight restriction bug when reselecting dates

### ISSUE THREAD

**Issue by charharhar** [krystalcampioni/vue-hotel-datepicker#31]
The exact issue can be found at your demo: https://krystalcampioni.github.io/vue-hotel-datepicker#minNights

There seems to be a bug that prevents me from reselecting dates that are within the minNight restriction. For example: I will choose two arbitrary dates as the checkIn and checkOut: 11-1-2017 as checkIn and 11-30-2017 as checkOut. When I want to reselect my checkIn and checkOut nights, I cannot choose any nights that are between 11-1-2017 and 11-5-2017, because they are disabled by minNights.

```
<HotelDatePicker
 :minNights="5">
</HotelDatePicker>
```

My expected behavior is that if I wanted to make changes to my checkIn and checkOut dates after I had already selected them both, there shouldn't be any restrictions. In my code I am trying the following:
```
updateMinDate() {
    if (!!this.$refs.hotelDatePicker.checkIn && !this.$refs.hotelDatePicker.checkOut) {
        this.applyMinDate = 7;
    } else {
        this.applyMinDate = 0;
    }
}
```
applyMinDate is a key in my component's data object, and updateMinDate() is a method invoked by the "checkInChanged" and "checkOutChanged" events that are emitted from the hotelDatePicker component.

What I want to accomplish is to only apply the minDate limitation on disabled dates when ONLY the checkIn date is selected. If both dates are selected and I wish to make changes to my checkIn and checkOut dates, there should not be a minNight restriction, NOT until I select a checkIn night and am currently selecting my checkOut night.

So far it seems to be working for me after adding that if else block, however its just a temporary fix.

**Comment by krystalcampioni** [comment]
Thanks for the feedback @charharhar 😬 

This is an intended behaviour as we don't want the `minNights` to influence in other types of restrictions such as `disabledDaysOfWeek`. The user can always clear the previous selection to choose a new range.  If you find a way. 

If you have a suggestion as how to make it work well with the other props, feel free to submit a PR.
