### ISSUE TITLE
disabledDaysOfWeek / disabledWeekDays page freeze when clicking the first date

### ISSUE THREAD

**Issue by micskubence** [krystalcampioni/vue-hotel-datepicker#312]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matiasperrone** [comment]
so? any code to reproduce?

**Comment by matiasperrone** [comment]
This seems bogus... so I am going to close it please reopen with more info

**Comment by filippodicostanzo** [comment]
I have the same issue.

The page freeze when clicking the first date.

`  <HotelDatePicker
                  :minNights="7"  :disabledDaysOfWeek="['Saturday']">
                </HotelDatePicker>`

If i remove this props the calendar works fine.

No error in javascript console.

Any solution?
