### ISSUE TITLE
disabledDaysOfweek doesn't work

### ISSUE THREAD

**Issue by micskubence** [krystalcampioni/vue-hotel-datepicker#313]
when i dont set disableddaysofweek everything works fine but as soon as i set it my whole app freezes

<template>
	<div>
		<HotelDatePicker
  :disabledDaysOfWeek="['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday']"
  :enableCheckout="true"
  :allowedRanges="[7,10,14]"
></HotelDatePicker>
	</div>
</template>

<script>
import HotelDatePicker from 'vue-hotel-datepicker'
import 'vue-hotel-datepicker/dist/vueHotelDatepicker.css';

export default {
  components: {
    HotelDatePicker,
  },
}
</script>
i did it just like the example in the documentation

**Comment by micskubence** [comment]
<template>
	<div>
		<HotelDatePicker
  :disabledDaysOfWeek="['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday']"
  :enableCheckout="true"
  :allowedRanges="[7,10,14]"
></HotelDatePicker>
	</div>
</template>

<script>
import HotelDatePicker from 'vue-hotel-datepicker'
import 'vue-hotel-datepicker/dist/vueHotelDatepicker.css';


export default {
  components: {
    HotelDatePicker,
  },
}
</script>

**Comment by matiasperrone** [comment]
Hi!! sorry about that, I am a little away from this project due to my current work.

Can you provide with a little more of code?

**Comment by matiasperrone** [comment]
This issue is related with #312
