### ISSUE TITLE
How can get value?

### ISSUE THREAD

**Issue by niusmake** [krystalcampioni/vue-hotel-datepicker#35]
Excuse me,

I read this document, But I can not find how to get the value of the method..

Please tell me what should I do,Thanks.

**Comment by krystalcampioni** [comment]
@niusmake I'm not sure I understood your doubt 🤔 You have two regular text input fields in the component, when the user selects the dates, the value of the inputs are updated to match the selected dates. Also, you can have the events `checkInChanged` and `checkOutChanged` that are emitted with the new dates as payload.

**Comment by niusmake** [comment]
Sorry,i'm so sorry i didn't make myself clear.
If my selects the dates , I want to get dates value.
like this:
`<template>
       <HotelDatePicker
         :value="date"
         @checkInChanged="checkin"
        >
       </HotelDatePicker>
</template>

<script>
  import HotelDatePicker from 'vue-hotel-datepicker'
  export default {
    components: {
        HotelDatePicker,
    },
    data () {
      return {
        date: '',
      }
    },
    methods: {
      checkin() {
          console.log(this.date);
      },
    }
  }
</script>
`
but I can't get this date value.

Please Tell me how can I do?

**Comment by krystalcampioni** [comment]
You have to use `$event` to access the payload this way:

```
       <DatePicker
         @checkInChanged="logCheckin($event)"
        >
       </DatePicker>
```

```
    methods: {
      logCheckin(date) {
        console.log(date);
      },
    }
```

or, you can access the event via $refs.

```
this.$refs.myDatepicker.$on('checkInChanged', (date) => {
       console.log(date)
});
```

Hope it helps 😄
