### ISSUE TITLE
Set Default Value

### ISSUE THREAD

**Issue by pawmanaloto** [krystalcampioni/vue-hotel-datepicker#38]
Hello Krystal,

I hope we can set a default value for the dates. The example on this repo isn't working,
`<HotelDatePicker :value="'2020-07-14 ► 2020-07-20'"/>`

I hope you can add something like this
`<HotelDatePicker :startingDateValue="'2020-07-14'" :endingDateValue="'2020-07-20'"/>`

Cheers

**Comment by key60529** [comment]
I spent an hour to figure out how to set the default value, and found nothing till I saw this opened issue, hope we can merge this and make it work :)

**Comment by krystalcampioni** [comment]
Merged and released a new version to NPM

https://github.com/krystalcampioni/vue-hotel-datepicker/pull/39
