### ISSUE TITLE
Can I enable all date befeore startDate

### ISSUE THREAD

**Issue by Sanbingo** [krystalcampioni/vue-hotel-datepicker#47]
### Description

Before startDate is disable, I cannot select it, how can I select date that i want？

![image](https://user-images.githubusercontent.com/5332100/34428947-ec33dc00-ec8c-11e7-8893-7878ecc90551.png)

**Comment by krystalcampioni** [comment]
All dates before the startDate will be disabled. If you need to be able to select a date before the one you currently have you should use update the startDate to an older date.

**Comment by Q-back** [comment]
or you can set startDate to `null`, but you'll end up opening calendar at 1970 :/

**Comment by riksnelders** [comment]
This... Can this be fixed? Anoying as hell, just using it as a regular datepicker
