### ISSUE TITLE
Unwanted behavior: clear button submitting parent form

### ISSUE THREAD

**Issue by charharhar** [krystalcampioni/vue-hotel-datepicker#50]
I am using the Hotel Datepicker component inside of a form element along with other inputs. Example:
```
<form>
    <input type="text" name="name">
    <hotel-date-picker></hotel-date-picker>
    <input type="email" name="email>
    <input type="submit" value="Send it">
</form>
```

Upon clicking on the clear button (button.datepicker__clear-button), it submits my entire form and causes a page refresh. I've tried the following but was unsuccessful.
```
const clearButton = querySelector('button.datepicker__clear-button');
clearButton.addEventListener('click', function(e) {
     e.preventDefault()
})
```

It only works when I inspect the element from my chrome devtools and added type="button" to the element.
```
<button class="datepicker__clear-button" type="button">＋</button>
```

Any other solutions to this issue besides the one I've mentioned?

**Comment by krystalcampioni** [comment]
Fixed by #41
