### ISSUE TITLE
How to change color of input:active?

### ISSUE THREAD

**Issue by anykarolyne** [krystalcampioni/vue-hotel-datepicker#52]
I want to change the color of the class .datepicker__dummy-input--is-active but i can't.

My vue component:
```
<template>
  <no-ssr>
    <HotelDatePicker class="color-active" :i18n="dateoptions.i18n" :format="dateoptions.format" DatePickerID="travel" @checkOutChanged="updateDateTo($event)" @checkInChanged="updateDateFrom($event)"/>
  </no-ssr>
</template>
```
My style:
```
.datepicker-label{
  font-weight: normal;
  color: #4182e0;
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
}
.color-active .datepicker__dummy-input--is-active{
  color: #4182e0;
}
```
When I change a color at class datepicker-label is working perfectly, but when is input:active not working. The strange is when I inspect the elements the modification appears, but the screen continues the default color(#00ca9d). 
![foto 1](https://user-images.githubusercontent.com/7489445/34733437-8431a8f0-f54f-11e7-91d8-0e05e1beb569.jpg)

### Datepicker Version
^2.0.11

**Comment by seifsay3d** [comment]
you can use !important, or write a more specific query selector.

**Comment by anykarolyne** [comment]
I used ::placeholder and working, like that:

`.datepicker__dummy-input--is-active::-moz-placeholder{color: #4182e0 !important;opacity: 1 !important;}
.datepicker__dummy-input--is-active::-webkit-input-placeholder{color: #4182e0 !important;opacity: 1 !important;}
.datepicker__dummy-input--is-active:-ms-input-placeholder{color: #4182e0 !important;opacity: 1 !important;}
.datepicker__dummy-input--is-active:-moz-placeholder{color: #4182e0 !important;opacity: 1 !important;}`

**Comment by patie** [comment]
please use external css, so we can easy customize style without !important, thank you
