### ISSUE TITLE
dinamically change startDate

### ISSUE THREAD

**Issue by clodoveo** [krystalcampioni/vue-hotel-datepicker#53]
Once component is mounted i cannot dinamically change startDate ( for example calling an api which returns hotel opening date )

**Comment by clodoveo** [comment]
well, not sure the best way , but resolved calling the api on beforeMount and using a v-if wich destroy and recreate the component.

**Comment by pawmanaloto** [comment]
Try to use the property startingDateValue
`startingDateValue='new Date(initDateValue)'`

**Comment by krystalcampioni** [comment]
@clodoveo the calendar is generated on `beforeMount` based on the value defined on the `startDate` so with the current implementation there's no better way of handling this 👍
