### ISSUE TITLE
iOS scrolling background of page instead of calendar; input focus problems; 

### ISSUE THREAD

**Issue by feliperaul** [krystalcampioni/vue-hotel-datepicker#57]
### Description

On iPhone X, iOS 11.2, Safari, if I open the demo page, the following problems occur:

- When I click on any example (can be the first one), I see the calendar fullscreen; when I try to scroll upwards to see the next months (only january and february are within the viewport), I see the back of the page scolling instead, and only after trying 5 or 10 times I can manage to scroll (just a little) of the calendar that is fullscreen on the foreground;

- As soon as I click on any example, I see a very large blue cursor blinking inside the calendar, exactly where the <input> was. Any ideas how to remove this? It's very bothersome and kind of ruins the UI, has a very weird feel to it. 

- Also, even tough I can't reproduce enough, 30% of my clicks in the calendar end up selecting the wrong date, don't know exactly why. 

### Code sample 
Not needed, it's in the default examples. 

### Datepicker Version

None, it's in the examples.

**Comment by mike-db88** [comment]
Can confirm. I tinkered with script a bit and it seems it just doesnt add overflow-hidden class to body on safari.

**Comment by chrisrenga** [comment]
same here. It looks like the readonly option does not work on mobile safari. 
I noticed that Airbnb gets around it by not using inputs. Instead they have a button to open the picker. There is also a zoom effect in IOS If the input font size is smaller then 16px https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone#answer-16255670

cant event get the other months to appear on an iPad. Only the first 2

**Comment by tbyte80** [comment]
Hello!
I found this issue because I having the same issue (on mobile it is a bit cumbersome to navigate through months. Often months wouldn't load especially on IOS). The button looks perfect to solve that but I cannot find how to activate it.
It doesn't appear on default and also in the examples I don't see it anywhere.
Any advice?

**Comment by janein** [comment]
I still experience this issue. Does anybody have a workaournd to this?

Otherwise - please reopen.
