### ISSUE TITLE
Feature request: set first day of week

### ISSUE THREAD

**Issue by mike-db88** [krystalcampioni/vue-hotel-datepicker#58]
It would be usefull to make prop setting that would allow to choose first day of week.
In some countries first day of week is usually monday, not sunday.

**Comment by ajayenuke** [comment]
By when it will be added? Any idea

**Comment by mike-db88** [comment]
By the way @ajayenuke, if you need this just modify getFIrstDay inside helpers.js to this:

`  getFirstSunday(date) {
    var firstDay =  this.getFirstDayOfMonth(date);
    return new Date(
      firstDay.setDate(
        firstDay.getDate()
        -firstDay.getDay() + 1
      )
    );
  },`

**Comment by krystalcampioni** [comment]
Included here: https://github.com/krystalcampioni/vue-hotel-datepicker/pull/48 👍
