### ISSUE TITLE
I am facing problem in Date format 'DD.MM.YYYY' is not acceptable as well as start day of week should be monday not sunday. 

### ISSUE THREAD

**Issue by ajayenuke** [krystalcampioni/vue-hotel-datepicker#60]
### Description

[Description of the bug or feature]

### Code sample 
[ If you are submitting a bug issue, paste your code so I can reproduce it, or a link to a Codepen with it ]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Datepicker Version

[ The version of the datepicker you have installed in your project ]

**Comment by amulchinock** [comment]
@ajayenuke - with regard to date format, are you talking about the date displayed by the UI, or the dates returned by the datepicker?

If you're talking about the UI (as in, what the user sees) - you can specify the format with the `format` prop.

For specifying the starting day of a week - you can use the `firstDayOfWeek` prop.

See [firstDayOfWeek](https://github.com/krystalcampioni/vue-hotel-datepicker#firstdayofweek) and [format](https://github.com/krystalcampioni/vue-hotel-datepicker#format) props in the docs.

**Comment by amulchinock** [comment]
@krystalcampioni should we mark this as closed now?
