### ISSUE TITLE
Close button does not have a prop and best to only show after input

### ISSUE THREAD

**Issue by mhimi1** [krystalcampioni/vue-hotel-datepicker#61]
### Description

It would be good to have a showCloseButton prop. Also, the close button should only show up after date(s) are selected instead of by default.

### Code sample 
[ If you are submitting a bug issue, paste your code so I can reproduce it, or a link to a Codepen with it ]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Datepicker Version
2.2.0
[ The version of the datepicker you have installed in your project ]

**Comment by krystalcampioni** [comment]
The close button is only displayed on the mobile version of the datepicker and while the calendar is open. Maybe you're referring the clear button ( the x on the right side of the input)?
That functionality could be improved for sure 👍 
Version 2.4.0 includes a new `displayClearButton` prop, and the x is only displayed if there are dates set. https://github.com/krystalcampioni/vue-hotel-datepicker/pull/94
