### ISSUE TITLE
open positioning top/bottom

### ISSUE THREAD

**Issue by sofianester** [krystalcampioni/vue-hotel-datepicker#72]
Hi need help!
On desktop, How to handle (open-to-top/open-to-bottom) depending on the input position ?
If the input is in the bottom of the screen. the datepicker should open to top.

![untitled-1](https://user-images.githubusercontent.com/4677073/39292090-4ec2f0ac-495f-11e8-8cdf-d8a980067f38.jpg)

**Comment by millerone** [comment]
This would be great. Please consider this feature. 
Thank you!

**Comment by egorzot** [comment]
+1

**Comment by matiasperrone** [comment]
Sorry but I didn't have the time to address this issue. Seems important.

**Comment by matiasperrone** [comment]
Check the new v4.0.0-beta.2

**Comment by matiasperrone** [comment]
@francescomugnai I've working on this please be patient, I think that some rewrites must be done first.
