### ISSUE TITLE
Allow change the start date when selecting a previous date

### ISSUE THREAD

**Issue by lmsmartins** [krystalcampioni/vue-hotel-datepicker#74]
### Description

Instead of blocking the dates before the selected start date, could we please allow user to simply change the start date when selecting a date before the current start date? I think it would be a bit more user friendly, since if user gets the start date wrong, the user has to select an end date first before changing the start date. I would like to help you on doing this, do you think this is something that could be done? If yes, could you please point me out in the right direction on how to do this? Which vue files contain the logic that I would have to work on?

[Description of the bug or feature]

### Code sample 
[ If you are submitting a bug issue, paste your code so I can reproduce it, or a link to a Codepen with it ]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
When a start date is already selected, we shouldn't block the previous dates. If user selects a date previous the current start date, then the start date would be simply changed to that new date the user has selected.

**Actual behavior:** [What actually happened]
When selecting a start date, all previous dates are blocked, and the user needs to set an end date before changing the start date.

### Datepicker Version
2.2.1
[ The version of the datepicker you have installed in your project ]

**Comment by matiasperrone** [comment]
This is solved in v4.0.0-beta.1. Please try it!
