### ISSUE TITLE
Missing i18n when using Fecha library to format dates (checkin and checkout inputs)

### ISSUE THREAD

**Issue by SnitramDev** [krystalcampioni/vue-hotel-datepicker#75]
### Description
Missing i18n when using Fecha library to format dates (see image attached).
Could
<img width="782" alt="screen shot 2018-06-03 at 17 14 42" src="https://user-images.githubusercontent.com/8367143/40889183-0b2cb600-6752-11e8-8859-6eea215fc50f.png">
 I please submit a PR? I have a fix for this.

[Description of the bug or feature]
Date formats within the inputs (checkin and checkout) are not using i18n.

### Code sample 
[ If you are submitting a bug issue, paste your code so I can reproduce it, or a link to a Codepen with it ]

### Steps to Reproduce

1. Set the date format to MMMM D
2. The month is not translated.

**Expected behavior:** [What you expected to happen]
Date formats within the inputs (checkin and checkout) should use i18n.

**Actual behavior:** [What actually happened]
Date formats within the inputs (checkin and checkout) aren't using i18n, and therefore, are not being translated.
### Datepicker Version

[ The version of the datepicker you have installed in your project ]

**Comment by krystalcampioni** [comment]
Will be released with the next version :)
