### ISSUE TITLE
FEATURE: Ability to check-in/check-out on the same day

### ISSUE THREAD

**Issue by nkoterba** [krystalcampioni/vue-hotel-datepicker#8]
Unless I'm missing some configuration of the props, I don't see any way to enable users to check-in and check-out on the same day (I know it's a slightly odd edge case but we of course need this feature).

Any plan to support this?

**Comment by krystalcampioni** [comment]
It's indeed an odd edge case 🤔 There are some checks on the code to prevent the user from selecting the same day for checkin and checkout. I'm currently working on v2 that will be a major rewrite of this component. I'll add this feature in the roadmap

**Comment by nkoterba** [comment]
Yes, we're using the component to pull up historical data and we'd like the ability to just pull a day's worth of data.  We've worked around it by setting the max date to be tomorrow and telling users if they want to select a single day they select the day they want and then the "next" day.

It's certainly not the best UX solution, but it works without having to fork your code or do other hacky things.

But an option or setting to check-in/out on the same day would be much appreciated.

**Comment by krystalcampioni** [comment]
@nkoterba I'll release v2.0.0 soon, and you'll be able to set the minNights to 0 if you want to allow checkIn and checkOut on the same day.
