### ISSUE TITLE
Bind-Model

### ISSUE THREAD

**Issue by nsimeonov** [krystalcampioni/vue-hotel-datepicker#82]
Probably obvious to anyone with more experience than me, but can you include in the examples how to bind to a model or how to get the selected date range in order to perform an API call?

**Comment by chrisrenga** [comment]
you can listen to the change events

Eg. 
```
        <HotelDatePicker
            @checkInChanged="updateCheckIn"
            @checkOutChanged="updateCheckOut"
            ...
        />
```
and handle the update by performing an action or simply by adding the value to your data

```
    methods: {
            updateCheckIn(date) {
                this.form.arrival = date;
            },

            updateCheckOut(date) {
                this.form.departure = date;
            },
    }
```

**Comment by krystalcampioni** [comment]
thanks for clarifying that @chrisrenga 🙏

**Comment by guillaumebriday** [comment]
I think this example should be in the readme.

Is it planned to add the support of `v-model` ?

Thank you for your work !
