### ISSUE TITLE
Feature request: Allow user to pass HTML to the tooltips

### ISSUE THREAD

**Issue by nkoterba** [krystalcampioni/vue-hotel-datepicker#9]
See graphics below.  Wrapping works fine on the right-side, but on the left, longer tooltips get clipped.

Clipped left-side tooltip:
![image](https://user-images.githubusercontent.com/2508944/30665340-b1f197e2-9e1e-11e7-9044-661d495d89fb.png)

Correctly wrapped right-side tooltip:
![image](https://user-images.githubusercontent.com/2508944/30665348-b8e8025c-9e1e-11e7-8c73-1d95b028b256.png)

Also, with the tooltip, it might be cool to allow HTML to be passed as tooltip using Vue's `v-html` directive.  I could wrap my tooltip text in several `<div>` to ensure default block wrapping but I see the tooltip just expects text to be returned from the callback function.

👍 On the great Vue component!

**Comment by krystalcampioni** [comment]
It's indeed a nice idea to be able to pass html to the tooltip  
I'll put in the roadmap. Feel free to submit a PR with this change if you want to contribute :)

**Comment by nkoterba** [comment]
@krystalcampioni I'm swamped with work and a few deadlines but I would like to contribute.  I'll try to find some time in the next few weeks to explore this feature.

**Comment by kjad** [comment]
I think I have a solution for this. Will put in a MR shortly
