### ISSUE TITLE
question: disable dates until date xy

### ISSUE THREAD

**Issue by zangab** [krystalcampioni/vue-hotel-datepicker#90]
### Description
I wan to disable all the dates that are e.g. before `today` - some other date pickers refer to this as `min-date` (minimum-date). The user shouldn't be able to select any date before that. In the docs there is a section called `disabledDates` but that just takes date strings as an array or can I pass in a function here?

**Comment by amulchinock** [comment]
Hi @zangab 
You can set a "minimim-date" with the `startDate` property. [See the documentation here.](https://github.com/krystalcampioni/vue-hotel-datepicker#startdate)

`disabledDates` would be useful in a scenario where you want to specify arbitrary dates that can not be selected (e.g your 'hotel' has bookings already, and you don't want to allow people to book then, or your 'hotel' is closed on certain days (Christmas .etc)).

**Comment by amulchinock** [comment]
@krystalcampioni Should we close this issue?
