### ISSUE TITLE
Externally call to change selected dates

### ISSUE THREAD

**Issue by gareth-ib** [krystalcampioni/vue-hotel-datepicker#92]
How can we set the current date of the widget after the widget is built on the page?

**Comment by amulchinock** [comment]
@gareth-ib Do you mean you want to change the selected dates (checkin / checkout) programmatically?

**Comment by gareth-ib** [comment]
yes, but I switched to another system so I could do it

**Comment by amulchinock** [comment]
OK. I can suggest to @krystalcampioni that this issue be tagged as a feature request. We'll update this thread with further developments.

**Comment by amulchinock** [comment]
@gareth-ib @krystalcampioni Interestingly, I've just come across a use case where I need to do exactly this. 😅

This might well be the next issue I work on after #11

**Comment by matiasperrone** [comment]
Solved in v4.0.0-beta.2
